Making variant 2
frontend-park-mail-ru/homework_2022_2 pull request #1
Opened 2022-09-04 15:49 UTC by Ivan-Bir

Меня зовут Иван Бирюков
Группа Web-21

2022-09-04 22:55 UTC, Sarafa2n requested changes
Привет! Добро пожаловать на курс Frontend.
Ты неплохо справился с дз0. Есть пару замечаний, давай их поправим, я верю что у тебя получится , если что пиши в телеграм sarafa2n
И еще, давай приведем в порядок стиль кода можно воспользоваться одним из этих стилей кода https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

2022-09-04 22:55 UTC, Sarafa2n commented on source/euclid.js
> +*/
Респект за JSDoc, давай добавим примеры использования

2022-09-04 22:55 UTC, Sarafa2n commented on source/euclid.js
> +euclid.copySortedArgs = arr => [...arr].sort( (a, b) => b - a );
Круто что используешь стрелочные функции, но можно было не выносить это в отдельную функцию

2022-09-04 22:55 UTC, Sarafa2n commented on source/euclid.js
> +    }
Давай здесь использовать один из методов Массива (map, reduce, forEach)

2022-09-04 22:55 UTC, Sarafa2n commented on source/euclid.js
> +euclid.forPair = function euclidForPair(greaterNum = 1, smallerNum = 1) {
Давай лучшее это просто отдельная функция, не будем в прототипы лезть)

2022-09-04 22:55 UTC, Sarafa2n commented on source/euclid.js
> +    }
Круто что позаботился об исключениях, только давай тип ошибок поправим

2022-09-04 22:55 UTC, Sarafa2n commented on source/euclid.js
> +    if (smallerNum > greaterNum) return euclidForPair(smallerNum, greaterNum);
а можем без рекурсии ?

2022-09-05 20:13 UTC, Sarafa2n requested changes

2022-09-05 20:13 UTC, Sarafa2n commented on source/max.js
> +const max = (numbers) => Math.max(...numbers);
зачем трогал, верни как было)

2022-09-05 20:13 UTC, Sarafa2n commented on source/euclid.js
> +    if (greaterNum === 1 || smallerNum === 1) return 1;
давай придерживаться style гайдов https://learn.javascript.ru/coding-style

2022-09-05 20:13 UTC, Sarafa2n commented on source/euclid.js
> +function euclid(...numbers) {
давай использовать стрелочные функции, ведь это молодежно

2022-09-05 20:13 UTC, Sarafa2n commented on source/euclid.js
> +* @inner
не нужно

2022-09-05 20:13 UTC, Sarafa2n commented on tests/euclid.js
> +			'Error thrown'
можно заменить на `new TypeError('')`

2022-09-05 20:13 UTC, Sarafa2n commented on source/euclid.js
> +        throw new SyntaxError('Function <euclid> was called without arguments');
лучше просто Error

2022-09-05 20:13 UTC, Sarafa2n commented on source/euclid.js
> +    while (residual !== 0) {
отступ нужен

2022-09-07 20:03 UTC, Betchika99 commented
ДЗ принято

2022-09-07 20:03 UTC, closed without merging