Максимова Елизавета
frontend-park-mail-ru/homework_2022_2 pull request #10
Opened 2022-09-05 20:36 UTC by Liza1040

2022-09-06 17:53 UTC, DPeshkoff requested changes
Привет!
Поздравляю с переходом на второй семестр и добро пожаловать на курс фронтенд-разработки)
Решение неплохое, но нужно кое-что исправить - оставил несколько комментариев. Если возникнут какие-то вопросы, можешь писать здесь или в [Телеграм](https://t.me/DmPesh))

2022-09-06 17:53 UTC, DPeshkoff commented on source/plainify.js
> +'use strict';
А для чего нужна эта строчка?

2022-09-06 17:53 UTC, DPeshkoff commented on source/plainify.js
> +const plainify = (nested, propertyName = '') => {
Круто, что ты используешь стрелочные функции! Подскажи, пожалуйста, в чем отличие стрелочных функций от обычных?

2022-09-06 17:53 UTC, DPeshkoff commented on source/plainify.js
> +
По требованиям задания к функциям должна быть написана документация [JSDoc](https://jsdoc.app)

2022-09-06 17:53 UTC, DPeshkoff commented on source/plainify.js
> +        return Object.assign(plainObj, value instanceof Object ? plainify(value, newPropertyName) : {[newPropertyName]: value}); // копирование свойств в целевой объект
Классное решение, но, Хьюстон, у нас проблема!

<img width="863" alt="Снимок экрана 2022-09-06 в 20 50 56" src="https://user-images.githubusercontent.com/31134795/188705015-9993d164-5605-42a7-9bcf-5f9f67bd1b94.png">

2022-09-06 17:53 UTC, DPeshkoff commented on source/plainify.js
> +
Не хватает еще проверки входных параметров)

2022-09-06 17:53 UTC, DPeshkoff commented on tests/plainify.js
>  	});
А что будет, если я передам туда что-то очень страшное? null, undefined, Infinity, NaN? Пустой объект? 

Подумай, на что еще можно было бы проверить функцию)

2022-09-06 20:08 UTC, Liza1040 commented on source/plainify.js
> +'use strict';
Она включает "строгий" режим. Он позволяет использовать более строгий режим JS для отлова ошибок.

2022-09-06 20:16 UTC, Liza1040 commented on source/plainify.js
> +const plainify = (nested, propertyName = '') => {
У стрелочных функций нет this и нет переменной arguments. И также их нельзя использовать с new.

2022-09-07 08:42 UTC, DPeshkoff commented on source/plainify.js
> +'use strict';
А можно ли писать код в строгом режиме без этой директивы?)

2022-09-08 17:40 UTC, DPeshkoff requested changes

2022-09-08 17:40 UTC, DPeshkoff commented on source/plainify.js
> +    if (typeof nested != 'object') {
Лучше использовать [строгие проверки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Equality_comparisons_and_sameness)

Кроме того - если я передам в функцию, например, `new String('test')` - я получу кое-что не очень приятное

<img width="745" alt="Снимок экрана 2022-09-08 в 20 28 58" src="https://user-images.githubusercontent.com/31134795/189187143-01665b21-9bbf-4234-9ded-a70965c38f6d.png">

Объяснишь, почему так происходит?)

2022-09-08 17:40 UTC, DPeshkoff commented on source/plainify.js
> +        throw new Error('Function argument must not be an empty object')
Здесь тоже можно TypeError)

И не забывай про ;

2022-09-08 17:40 UTC, DPeshkoff commented on source/plainify.js
> +    const propertyArray = Object.entries(nested); //получаем массив свойств объекта
`return` можно прямо тут - можно дописывать методы прямо к `Object.entries()`, а лишняя переменная, кажется, не нужна)

2022-09-08 17:40 UTC, DPeshkoff commented on source/plainify.js
> +        return Object.assign(plainObj, typeof value === 'object' ? plainify(value, newPropertyName) : {[newPropertyName]: value}); // копирование свойств в целевой объект
Если у нас где-то попадется условный пустой массив, то мы получим просто ошибку (хотя до этого рекурсивного вызова все шло хорошо, например)

Как ты думаешь, как можно это исправить?)

2022-09-08 17:40 UTC, DPeshkoff commented on source/plainify.js
> +    const callbackFunction = (plainObj, [key, value]) => {
Эту функцию можно сделать анонимной и отправить прямо в место ее вызова на строке 42

2022-09-08 17:40 UTC, DPeshkoff commented on tests/plainify.js
> +			function () {plainify(5);},
Такс такс такс
А что тут делают обычные функции? Для чего это?

2022-09-08 17:40 UTC, DPeshkoff commented on tests/plainify.js
> +			function (err) {return err.toString() === 'TypeError: Invalid data was passed to the function'},
Здесь происходит что-то страшное
Давай здесь тоже создавать TypeError - так мы обойдемся без этих страшных функций

2022-09-08 17:40 UTC, DPeshkoff commented on tests/plainify.js
> +
А если я подам на вход массив? Или функцию?

2022-09-08 20:22 UTC, Liza1040 commented on source/plainify.js
> +    if (typeof nested != 'object') {
Ой, точно. Потому что оператор new создает экземпляр объекта

2022-09-08 20:59 UTC, Liza1040 commented on source/plainify.js
> +    const callbackFunction = (plainObj, [key, value]) => {
А тогда к ней должна быть написана документация JSDoc?

2022-09-08 21:23 UTC, Liza1040 commented on source/plainify.js
> +        return Object.assign(plainObj, typeof value === 'object' ? plainify(value, newPropertyName) : {[newPropertyName]: value}); // копирование свойств в целевой объект
Добавить проверку?

2022-09-08 21:34 UTC, DPeshkoff commented on source/plainify.js
> +        return Object.assign(plainObj, typeof value === 'object' ? plainify(value, newPropertyName) : {[newPropertyName]: value}); // копирование свойств в целевой объект
Да, но можно оптимизировать, чтобы не писать кучу ифов два раза)

2022-09-08 21:40 UTC, DPeshkoff commented on source/plainify.js
> +    if (!(typeof nested === 'object')) {
можно просто` !== `

2022-09-08 21:42 UTC, DPeshkoff commented on source/plainify.js
> +    const callbackFunction = (plainObj, [key, value]) => {
Нет, не обязательно - документация нужна для других пользователей, а эту анонимная функция отдельно они не вызовут)

2022-09-08 22:09 UTC, Liza1040 commented on tests/plainify.js
> +
Если подать на вход пустой массив, то этот тест сработает. А если подать функцию, то сработает тест 7 и выведется ошибка " Invalid data was passed to the function"

2022-09-08 22:12 UTC, Liza1040 commented on source/plainify.js
> +    const callbackFunction = (plainObj, [key, value]) => {
Поняла, спасибо

2022-09-08 22:15 UTC, Liza1040 commented on source/plainify.js
> +        return Object.assign(plainObj, typeof value === 'object' ? plainify(value, newPropertyName) : {[newPropertyName]: value}); // копирование свойств в целевой объект
А как оптимизировать?

2022-09-08 22:52 UTC, Liza1040 commented on tests/plainify.js
> +			function () {plainify(5);},
Первым аргументом функции throws() должна быть функция, содержащая код, который выдает ошибку. Нигде в интернете не нашла точного ответа, почему нужна именно функция. Могу предположить, это чтобы формат сообщения об ошибке был приведен к типу ошибки.

2022-09-08 23:05 UTC, DPeshkoff commented on source/plainify.js
> +        return Object.assign(plainObj, typeof value === 'object' ? plainify(value, newPropertyName) : {[newPropertyName]: value}); // копирование свойств в целевой объект
Вынести все условия по проверке в одну функцию и вызывать ее)

2022-09-08 23:05 UTC, DPeshkoff commented on tests/plainify.js
> +			function () {plainify(5);},
Можно же стрелочную)

2022-09-08 23:09 UTC, DPeshkoff requested changes

2022-09-08 23:09 UTC, DPeshkoff commented on source/plainify.js
> +    if (typeof nested !== 'object') {
new String все еще пройдет, кстати, давай это поправим - кажется, что это все-таки невалидный инпут

2022-09-08 23:14 UTC, DPeshkoff commented on source/plainify.js
> +    if (typeof nested != 'object') {
[Подробнее о происходящем](https://learn.javascript.ru/prototype-inheritance))

2022-09-09 14:53 UTC, DPeshkoff requested changes
Осталось совсем чуть-чуть)

2022-09-09 14:53 UTC, DPeshkoff commented on source/plainify.js
> +    if (typeof nested !== 'object' || nested instanceof String) {
Лучше отсекать не только строки, а все, что не plain-objet

2022-09-09 14:53 UTC, DPeshkoff commented on source/plainify.js
> +    if (Object.keys(nested).length == 0) {
Строгая проверка)

2022-09-09 14:53 UTC, DPeshkoff commented on source/plainify.js
> +            return {[propertyName]: undefined};
Для удобства чтения кода лучше не пребрегать {}

2022-09-11 12:31 UTC, DPeshkoff requested changes

2022-09-11 12:31 UTC, DPeshkoff commented on source/plainify.js
> +    if (!Object.prototype.isPrototypeOf(nested) || nested.constructor !== Object) {
Проверки на falsy тоже можно оставить)

2022-09-11 12:34 UTC, DPeshkoff requested changes

2022-09-11 12:34 UTC, DPeshkoff commented on source/plainify.js
> +            typeof value === 'object' ? plainify(value, newPropertyName) : {[newPropertyName]: value}); // копирование свойств в целевой объект
Тут проверка на type object(

2022-09-11 12:34 UTC, DPeshkoff commented on source/plainify.js
> +const plainify = (nested, propertyName = '') => {
Давай еще проверим propertyName?

2022-09-11 21:27 UTC, DPeshkoff requested changes

2022-09-11 21:27 UTC, DPeshkoff commented on source/plainify.js
> +        if (nested === undefined || nested === null || !Object.prototype.isPrototypeOf(nested) || nested.constructor !== Object || typeof propertyName !== 'string') {
Можно вместо первых двух проверить [так](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)

2022-09-13 13:56 UTC, DPeshkoff approved these changes

2022-09-14 15:27 UTC, Betchika99 commented
ДЗ принято

2022-09-14 15:27 UTC, closed without merging