Ситниченко Софья #4
frontend-park-mail-ru/homework_2022_2 pull request #11
Opened 2022-09-06 22:36 UTC by sonichka-s

2022-09-07 05:41 UTC, maksongold commented
Привет!) Поздравляю с переходом на 2 семестр) Меня зовут Макс и я буду проверять твое дз0. Если будут какие-то вопросы/пожелания/мемы пиши https://t.me/maksongold.

2022-09-07 05:51 UTC, SergTyapkin requested changes

2022-09-07 05:51 UTC, SergTyapkin commented on source/inverse.js
> + * @param {array} массив элементов, который требуется инвертировать.
Синтаксис JSDoc:
`@param {Тип} Имя - Описание`
То есть в этом случае
`@param {array} array - массив эле...`

При этом типы должны быть одними из встроенных в JS.
Типа Integer здесь (в JS) увы, нет. Так что в следующей строке следует написать что-то вроде:
`@param {number} index - элемент... неизменным. Целый, неотрицательный.`

2022-09-07 05:51 UTC, SergTyapkin commented on source/inverse.js
> +const inverse = (array, index) => {
Расскажи, почему здесь ты решила сделать стрелочную функцию, а не обычную?

2022-09-07 05:51 UTC, SergTyapkin commented on source/inverse.js
> + 				result = array.splice(0, array.length + index).reverse().concat(array);
Никогда не используй тернарный оператор с большой вложенностью. Это практически не читается.
Он нужен для простых проверок, где if действительно излишен. Тут же явно лучше прописать логику через if.
Не экономь строчки кода в ущерб читаемости.

2022-09-07 05:51 UTC, SergTyapkin commented on source/inverse.js
> + 				result = array.splice(0, array.length + index).reverse().concat(array);
Никогда не используй тернарный оператор с большой вложенностью. Это практически не читается.
Он нужен для простых проверок, где if действительно излишен. Тут же явно лучше прописать логику через if.
Не экономь строчки кода в ущерб читаемости.

2022-09-07 05:51 UTC, SergTyapkin commented on source/inverse.js
> + 				result = array.splice(0, array.length + index).reverse().concat(array);
Причём через несколько
```JS
if (...) {
    ... 
    return ...;
} 
```

2022-09-07 05:51 UTC, SergTyapkin commented on source/inverse.js
> + 			index > 0 ? result = array.splice(0, index).concat(array.reverse()) :
Метод `splice` изменяет массив.
Массив - сложный тип, так что при передаче его в функцию он не копируется. Получается, что ты изменишь массив и снаружи функции. Попробуй вывести его после выполнения функции, и он будет уже другой.
Так что либо используй slice, либо делай копию массива

2022-09-07 05:51 UTC, SergTyapkin commented on tests/inverse.js
> +		  },
Тут отступ должен быть перед аргументами.

```js
foo(a, b);
// с переносами:
foo(
    a, 
    b
);

// Ну а если один из параметров - тоже функция или объект, то так же раскладывается:
foo((a) => {
       ... 
    }, 
    b
);
```

2022-09-07 05:51 UTC, SergTyapkin commented on tests/inverse.js
> +		  Error('Unexpected array parameter!'));
`Error`ы с одинаковым описанием лучше вынести в переменную, а не писать каждый раз текст одинаковый

2022-09-07 05:51 UTC, SergTyapkin commented on tests/inverse.js
> +		  Error('Unexpected array parameter!'));
`Error`ы с одинаковым описанием лучше вынести в переменную, а не писать каждый раз текст одинаковый

2022-09-07 05:53 UTC, SergTyapkin commented
В общем я тоже начал это все проверять,  но забыл поставить лейбл, и начал проверку ещё один ментор.
Так что будет у тебя два фидбека.
Мне в телегу можно писать сюда: t.me/tyapkin_s

2022-09-07 13:19 UTC, sonichka-s commented on source/inverse.js
> +const inverse = (array, index) => {
В данной ситуации она используется с целью сокращения и  упрощения кода

2022-09-07 21:10 UTC, SergTyapkin requested changes
К сожалению, осталось ещё пару замечаний

2022-09-07 21:10 UTC, SergTyapkin commented on source/inverse.js
> +	let arr = array.slice();
Здесь const, а не let.
Чтобы было проще - для сложных типов (классы, массивы, объекты, ...) при объявлении в 99% случаев на практике будет использоваться const.  Очень редко нужно изменять саму переменную со ссылкой на объект, а не внутренности этого объекта

2022-09-07 21:10 UTC, SergTyapkin commented on source/inverse.js
> + 	if (index > 0) return arr.splice(0, index).concat(arr.reverse());
У тебя какая-то страсть экономить строчки кода)
Переносы всегда читаются намного лучше)

2022-09-07 21:10 UTC, SergTyapkin commented on source/inverse.js
> + * @return {array} arr - массив для копирования передаваемого массива, с которым происходит работа в функции.
Надо ещё через тэг `@throws` (https://jsdoc.app/tags-throws.html) прописать возможные выдаваемые ошибки. Причём их лучше заменить на TypeError

2022-09-07 21:10 UTC, SergTyapkin commented on source/inverse.js
> + 	return arr.reverse();
Вот, супер, вся логика читаемая стала, молодец)

2022-09-07 23:24 UTC, sonichka-s commented on source/inverse.js
> + 	if (index > 0) return arr.splice(0, index).concat(arr.reverse());
Эта старая привычка..

2022-09-08 18:18 UTC, SergTyapkin approved these changes
Вот теперь всё красиво стало. Молодец ;)

2022-09-10 22:09 UTC, Betchika99 commented
ДЗ принято. Советую почитать про [деструктуризацию](https://t.me/makingweb/107). Это более удобный способ делать копию массива

2022-09-10 22:09 UTC, closed without merging