Мильченко Иван (Вариант 19)
frontend-park-mail-ru/homework_2022_2 pull request #12
Opened 2022-09-07 09:34 UTC by themilchenko

2022-09-07 15:09 UTC, SergTyapkin commented
Привет. Поздравляю с окончанием прошлого семестра и началом нового <s>круга ада</s>.
Моя задача, как ментора, максимально упростить и сделать максимально комфортным твоё обучение в следующие 4 месяца.
По любым вопросам, да и просто поболтать, можно писать мне в ТГ :) 
https://t.me/tyapkin_s

2022-09-07 15:23 UTC, SergTyapkin commented on source/sorting.js
> +    } else if (key.length == 1) {
Зачем else, если на строчке до этого есть return?

2022-09-07 15:24 UTC, SergTyapkin commented on source/sorting.js
> +        numbers.sort(byField(key));
Ты сам пишешь в требованиях в JSDoc, что функция не должна изменять преданный в неё массив.
А теперь ответь на вопрос - что делает метод `Array.sort`?

2022-09-07 15:25 UTC, SergTyapkin commented on source/sorting.js
> +        numbers.sort(function (left, right) {
В таком лучше стрелочная функция. Это как lambda-функция в других языках

2022-09-07 15:27 UTC, SergTyapkin commented on source/sorting.js
> +    } else if (key.length == 2) {
Почему ты обрабатываешь только массив свойств максимальной длины 2?
В задании необходимо обрабатывать массив неограниченной длины

2022-09-07 15:28 UTC, SergTyapkin commented on source/sorting.js
> +            let secondOrder = left[key[constants.secondElement]] - right[key[constants.secondElement]];
Тут const, а не let. Эта переменная ведь больше нигде не изменяется

2022-09-07 15:30 UTC, SergTyapkin commented on source/sorting.js
> +function sorting(numbers, key) {
Нужна проверка на входные аргументы. Что если передан какой-то мусор? Не два массива, а, скажем NaN и null?

2022-09-07 15:31 UTC, SergTyapkin commented on tests/sorting.js
> +			{ prop1: 4, id: '2' }
Ещё нужны тесты, где ты как раз и пытаешься передать в функцию всякий мусор.
И еще если этот мусор лежит в полях объекта

2022-09-07 15:32 UTC, SergTyapkin commented
Отпиши, пожалуйста, в ТГ, когда исправишь 😉

2022-09-09 06:35 UTC, SergTyapkin requested changes
Чересчур намудрил

2022-09-09 06:35 UTC, SergTyapkin commented on source/sorting.js
> +function sorting(numbers, key) {
Почему вообще входной массив называется numbers? Там ведь объекты

2022-09-09 06:35 UTC, SergTyapkin commented on source/sorting.js
> +    numbers.sort(function (left, right) {
Функция не должна менять исходный массив. `Array.sort` изменяет массив, к которому применяется.

2022-09-09 06:35 UTC, SergTyapkin commented on source/sorting.js
> +        let orderArray = [];
Ссылка на массив не изменяется. Изменяется его содержимое. Так что const

2022-09-09 06:35 UTC, SergTyapkin commented on source/sorting.js
> +        key.forEach((item) => {
Зачем сортировать сразу по всем свойствам?
Не лучше ли сравнивать их значении по очереди, и при первом несовпадении возвращать результат сравнения?

2022-09-09 06:35 UTC, SergTyapkin commented on source/sorting.js
> +        key.forEach((item) => {
P. S. В таком случае понадобится не `forEach`, а обычный `for (... of ...)`

2022-09-09 06:35 UTC, SergTyapkin commented on source/sorting.js
> +            if (typeof (left[item]) == 'string') {
Надо строгое сравнение

2022-09-09 14:05 UTC, SergTyapkin requested changes

2022-09-09 14:05 UTC, SergTyapkin commented on source/sorting.js
> + * @return sorted array according rules.
`@return {Array} `

2022-09-09 14:05 UTC, SergTyapkin commented on source/sorting.js
> +    const copyToArray = dataArray;
Эта строчка ничего не изменила. Сейчас обе эти переменные ссылаются на один и тот же массив. И, значит, он все так же будет меняться снаружи.
Тебе нужно создать копию массива.
Для этого можно использовать метод `Array.concat()`, например.

2022-09-09 14:05 UTC, SergTyapkin commented on source/sorting.js
> +    copyToArray.sort(function (left, right) {
Стрелочная функция нужна

2022-09-09 15:15 UTC, SergTyapkin approved these changes

2022-09-16 06:32 UTC, SergTyapkin requested changes

2022-09-16 06:32 UTC, SergTyapkin commented on source/sorting.js
> +    let pivot = dataArray[0];
Const

2022-09-16 06:32 UTC, SergTyapkin commented on source/sorting.js
> +    if ((dataArray === []) || (keyArray === [])) {
Зачем вообще тогда эта проверка, если есть length?

2022-09-16 17:23 UTC, Betchika99 commented
ДЗ принято

2022-09-16 17:23 UTC, closed without merging