Кашапов Альберт (8 Вариант)
frontend-park-mail-ru/homework_2022_2 pull request #13
Opened 2022-09-07 09:42 UTC by zeronethunter

2022-09-07 16:11 UTC, SergTyapkin requested changes
Надо немножко поправить. В целом все круто. Отпиши, пожалуйста, в ТГ, как будет готово

2022-09-07 16:11 UTC, SergTyapkin commented on source/sort.js
> +            words[index] = word.replace(/^./, word[0].toUpperCase());
Регулярки - это круто, но зачем, когда есть `Array.splice`?

2022-09-07 16:11 UTC, SergTyapkin commented on source/sort.js
> +    return words.sort(collator.compare).join(' ')
А если слова в предложении разделены, скажем, тремя пробелами? Все сработает?
И тест на это тоже нужен

2022-09-07 16:11 UTC, SergTyapkin commented on source/sort.js
> +const sort = (str) => {
Нужна проверка на входные параметры. Что str - это действительно строка, а не объект, или, скажем, NaN

2022-09-07 16:14 UTC, zeronethunter commented on source/sort.js
> +    let collator = new Intl.Collator()
Иначе, например, при вводе жёедгвба, программа выдавала Абвгдежё. То есть были проблемы с русским языком)

2022-09-07 16:15 UTC, zeronethunter commented on source/sort.js
> +            words[index] = word.replace(/^./, word[0].toUpperCase());
Мне показалось, что так будет работать быстрее:)

2022-09-08 05:49 UTC, zeronethunter commented on source/sort.js
> +    return words.sort(collator.compare).join(' ')
Тест на это уже есть, и не один. В разделе "Функция работает  правильно"

2022-09-08 18:08 UTC, SergTyapkin approved these changes

2022-09-14 16:21 UTC, SergTyapkin requested changes
Небольшие косяки оформления опять

2022-09-14 16:21 UTC, SergTyapkin commented on source/sort.js
> +const quickSort = (arr, compare = (left, right) => { return left > right }) => {
```js
(left, right) => { return left > right; } // и ещё ты ; забыл тут
```
Эквивалентно
```js
(left, right) => left > right
```

2022-09-14 16:21 UTC, SergTyapkin commented on source/sort.js
> + */
Вообще говоря, типы в JSDoc пишутся с маленькой буквы, но это не так важно

2022-09-14 16:21 UTC, SergTyapkin commented on source/sort.js
> +    if (arr.length < 2) return arr;
Не жалей переносов

2022-09-14 16:21 UTC, SergTyapkin commented on source/sort.js
> +    for (let i = 1; i < arr.length; i++) {
Почему не forEach?

2022-09-14 16:21 UTC, SergTyapkin commented on source/sort.js
> + * @throws {TypeError} Argument is not a string.
Тут можно оставить регистр как есть, потому что это не простой тип

2022-09-14 16:21 UTC, SergTyapkin commented on source/sort.js
> +    if (typeof str != 'string') {
Строгое сравнение

2022-09-14 16:21 UTC, SergTyapkin commented on source/sort.js
> +        let sortedWord = quickSort(word.split(''), collator.compare).join('');
Const

2022-09-14 16:21 UTC, SergTyapkin commented on source/sort.js
> +    let pivot = arr[0];
Const

2022-09-14 16:21 UTC, SergTyapkin commented on tests/sort.js
> +			sort(228)
Забыл ;

2022-09-14 16:21 UTC, SergTyapkin commented on tests/sort.js
> +			sort(sort(228))
Как и тут

2022-09-15 02:12 UTC, SergTyapkin approved these changes

2022-09-15 09:25 UTC, Betchika99 commented
ДЗ принято

2022-09-15 09:25 UTC, closed without merging