set function implemented
frontend-park-mail-ru/homework_2022_2 pull request #14
Opened 2022-09-07 10:25 UTC by yurij-lyubskij

2022-09-07 18:07 UTC, SergTyapkin commented
Привет. Поздравляю с окончанием прошлого семестра и началом нового <s>круга ада</s>.
Моя задача, как ментора, упростить и сделать максимально комфортным твоё обучение в следующие 4 месяца.
По любым вопросам, да и просто поболтать, можно писать мне в ТГ :) 
https://t.me/tyapkin_s

2022-09-07 20:57 UTC, SergTyapkin requested changes
Все работает, но надо предусмотреть проверку входных параметров, и ещё всякие мелочи.
Как поправишь - отпиши, пожалуйста, в ТГ. Так быстрее будет)

2022-09-07 20:57 UTC, SergTyapkin commented on source/set.js
> + * @returns {string|TypeError} - измененный объект
Returns лучше в конце писать

2022-09-07 20:57 UTC, SergTyapkin commented on source/set.js
> + * @returns {string|TypeError} - измененный объект
Функция не возвращает объект ошибки, а "выкидывает" исключение.
Для этого есть тэг throws: https://jsdoc.app/tags-throws.html

2022-09-07 20:57 UTC, SergTyapkin commented on source/set.js
> + * @param o - исходный объект
Не делай однобуквенные названия переменных

2022-09-07 20:57 UTC, SergTyapkin commented on source/set.js
> + * @param o - исходный объект
Не делай однобуквенные названия переменных

2022-09-07 20:57 UTC, SergTyapkin commented on source/set.js
> + * @param o - исходный объект
Тип каждого параметра тоже должен быть указан

2022-09-07 20:57 UTC, SergTyapkin commented on source/set.js
> +const set = (o, path, val) => {
Расскажи, почему тут стрелочная функция, а не обычная

2022-09-07 20:57 UTC, SergTyapkin commented on source/set.js
> +        while (keys.length > 1) {
В JS есть встроенные методы, работающие гораздо быстрее обычных C-style циклов. В этом случае было бы удобно и следует использовать метод `Array.reduce`

2022-09-07 20:57 UTC, SergTyapkin commented on source/set.js
> +        if (k === "") {
Как k может быть равно пустой строке, если k - это массив?

2022-09-07 20:57 UTC, SergTyapkin commented on source/set.js
> +        return o
Лучше не возвращать изменённый объект. Функция модифицирует исходный преданный в неё объект, а не создаёт новый. Так что воизбежание путаницы лучше вообще не возвращать значения.

2022-09-07 20:57 UTC, SergTyapkin commented on source/set.js
> +const set = (o, path, val) => {
Нужна проверка на типы входных параметров. Что не переданы какие-то NaN, null, и т.П.

2022-09-07 20:57 UTC, SergTyapkin commented on tests/set.js
> +    });
Это всё были, так называемые, позитивные тесты. Проверка на то, что функция работает правильно при нормальных переданных параметрах.
Теперь негативные тесты -
1. Закидываем в функцию всякий мусор вместо параметров, вроде NaN, null, и т. П.
2. Указываем некорректные пути

2022-09-07 20:57 UTC, SergTyapkin commented on tests/set.js
> +    });
Ну и в реализации функции тоже надо все это предусмотреть, конечно же

2022-09-08 15:07 UTC, yurij-lyubskij commented on source/set.js
> + * @returns {string|TypeError} - измененный объект
переместил

2022-09-08 15:07 UTC, yurij-lyubskij commented on source/set.js
> + * @returns {string|TypeError} - измененный объект
переместил

2022-09-08 15:15 UTC, yurij-lyubskij commented on source/set.js
> + * @returns {string|TypeError} - измененный объект
исправил

2022-09-08 15:19 UTC, yurij-lyubskij commented on source/set.js
> + * @param o - исходный объект
поменял

2022-09-08 15:20 UTC, yurij-lyubskij commented on source/set.js
> + * @param o - исходный объект
поменял

2022-09-08 15:28 UTC, yurij-lyubskij commented on source/set.js
> + * @param o - исходный объект
указал

2022-09-08 15:28 UTC, yurij-lyubskij commented on source/set.js
> + * @param o - исходный объект
указал

2022-09-08 16:05 UTC, yurij-lyubskij commented on source/set.js
> +        while (keys.length > 1) {
Использовал

2022-09-08 16:06 UTC, yurij-lyubskij commented on source/set.js
> +        if (k === "") {
k - элемент массива. Теперь проверяю длину в начале

2022-09-08 16:09 UTC, yurij-lyubskij commented on source/set.js
> +        return o
Исходные тесты, написанные не мной, проверяют возвращаемое функцией значение. В условии написано, что тесты задают логику работы программы. Поэтому возвращать значение необходимо.

2022-09-08 16:30 UTC, yurij-lyubskij commented on source/set.js
> +const set = (o, path, val) => {
Добавил проверки. Но val, например, согласно тестам, может быть null

2022-09-08 16:46 UTC, yurij-lyubskij commented on tests/set.js
> +    });
1) Добавил тесты, где функция кидает исключение из-за типа
2) Считаем, что путь всегда корректен. Согласно исходным тестам, если пути не существует, то мы его создаем.
Если путь пустой, то вместо исходного объекта возвращаем val.

2022-09-08 17:27 UTC, yurij-lyubskij commented on source/set.js
> +const set = (o, path, val) => {
Стрелочная функция не создает собственный контекст исполнения, она использует внешний. Это упрощает ее использование, как колбэка внутри метода или вместо метода в классе. (Удобно использовать почти всегда, когда функция будет выполняться где-то еще) У нее также нет arguments, поэтому ее удобно использовать в качестве, например, декоратора. Из-за удобства имеет смысл использовать стрелочные функции максимально часто.

2022-09-08 18:21 UTC, SergTyapkin commented on source/set.js
> +        return o
Справедливо. Я не посмотрел в исходные тесты

2022-09-08 18:36 UTC, SergTyapkin requested changes

2022-09-08 18:36 UTC, SergTyapkin commented on source/set.js
> +        if (typeof path != "string" || typeof obj != "object" || typeof val == "undefined") {
Нужно строгое сравнение. `!==` и `===`

2022-09-08 18:36 UTC, SergTyapkin commented on source/set.js
> +        keys.reduce(function (object, key, index, array) {
Здесь лучше использовать стрелочную функцию. Это как lambda-функция из других языков.
Очень удобная штука, причем не только в таких случаях.

2022-09-08 18:36 UTC, SergTyapkin commented on source/set.js
> +        keys.reduce(function (object, key, index, array) {
Кстати, раз ты не используешь `index` и `array`, то можно их и не указывать в аргументах

2022-09-08 18:36 UTC, SergTyapkin commented on source/set.js
> +        return obj
А ещё ты `;` позабывал)
В идеале твоё решение должно быть обработано линтером

2022-09-08 18:36 UTC, SergTyapkin commented on source/set.js
> +            throw TypeError("Incorrect Path")
А почему ты думаешь, что некорректный путь - это только тот, где нет `.`?

Например, для объекта:
```js
const obj = {
    key1: val1,
    key2: val2,
    key3: {
        key1: val1,
    }
}
```

Некорректны будут пути:
```js
obj.key1.smth
obj.key3.key1.smth
obj.smth
.
smth
```

На такие пути тоже нужна проверка. Причем, внутри `reduce`, как я её вижу

2022-09-08 19:13 UTC, yurij-lyubskij commented on source/set.js
> +            throw TypeError("Incorrect Path")
в исходном тесте "set работает правильно c объектами с существующими свойствами" программа подменяет существующую строку числом. В другом тесте создает вложенный путь. Так что приведенные в качестве примера пути корректны, как я понял

2022-09-08 20:01 UTC, yurij-lyubskij commented on source/set.js
> +            throw TypeError("Incorrect Path")
obj.smth - корректный путь. Согласно тестам создаем новое свойство

2022-09-09 07:38 UTC, SergTyapkin approved these changes

2022-09-14 16:34 UTC, SergTyapkin requested changes

2022-09-14 16:34 UTC, SergTyapkin commented on source/set.js
> + * @param {string} path - путь к свойству
Строго говоря,  встроенные типы принято писать в JSDoc с маленькой буквы, но это не особо принципиально

2022-09-14 16:34 UTC, SergTyapkin commented on source/set.js
> +    if (typeof val === 'undefined') {
Такое можно проверять строгим сравнением.
`val === undefined`

2022-09-14 16:34 UTC, SergTyapkin commented on tests/set.js
> +		assert.throws(() => set(object1, '.path',), TypeError('Invalid Argument: val is undefined'));
`,` после второго аргумента не нужна

2022-09-14 16:34 UTC, SergTyapkin commented on tests/set.js
> +				{foobar: '42'},
`, ` после последнего элемента списка / объекта  не должно быть

2022-09-14 16:34 UTC, SergTyapkin commented on tests/set.js
> +				{foobar: '42'},
Тоже,

2022-09-14 16:34 UTC, SergTyapkin commented on tests/set.js
> +		assert.throws(() => set(object1, '.path',), TypeError('Invalid Argument: val is undefined'));
Либо можно после неё проблем поставить, чтобы показать, что мы нарочно аргумент пропустили, хотя он там мог бы быть. Обычно так не делают, но этот случай, скорее, исключение

2022-09-14 16:34 UTC, SergTyapkin commented on tests/set.js
> +				key1: 'val3',
Тоже,

2022-09-14 16:34 UTC, SergTyapkin commented on tests/set.js
> +			},
Тоже,

2022-09-14 16:34 UTC, SergTyapkin commented on tests/set.js
> +				key1: 'val3',
Тоже ч

2022-09-14 16:49 UTC, yurij-lyubskij commented on source/set.js
> +    if (typeof val === 'undefined') {
fixed

2022-09-14 16:50 UTC, yurij-lyubskij commented on tests/set.js
> +		assert.throws(() => set(object1, '.path',), TypeError('Invalid Argument: val is undefined'));
убрал

2022-09-14 16:51 UTC, yurij-lyubskij commented on tests/set.js
> +				{foobar: '42'},
убрал

2022-09-14 16:51 UTC, yurij-lyubskij commented on tests/set.js
> +				key1: 'val3',
убрал

2022-09-14 16:52 UTC, yurij-lyubskij commented on tests/set.js
> +				{foobar: '42'},
убрал

2022-09-14 16:52 UTC, yurij-lyubskij commented on tests/set.js
> +			},
убрал

2022-09-14 16:53 UTC, yurij-lyubskij commented on tests/set.js
> +				key1: 'val3',
убрал

2022-09-14 17:59 UTC, yurij-lyubskij commented
Исправил

2022-09-15 18:37 UTC, SergTyapkin approved these changes
Хорош)

2022-09-16 17:20 UTC, closed without merging

2022-09-16 17:20 UTC, Betchika99 commented
ДЗ принято