Гапоян Иван Variant 5
frontend-park-mail-ru/homework_2022_2 pull request #15
Opened 2022-09-07 10:46 UTC by Loen15

2022-09-07 20:45 UTC, Shureks-den commented
Привет, я Саша, я буду проверять твое дз. Для оперативной связи со мной можешь стучать в личку https://t.me/alexklonov

2022-09-07 20:58 UTC, Shureks-den requested changes

2022-09-07 20:58 UTC, Shureks-den commented on source/chess.js
> +    size = Number( size );
Давай для этого использовать отдельную переменную, в твоем случае это не так критично, но в некоторых случаях это может превратить функцию в 'грязную', а мы все тут за чистый код :) 
Твое первое теоретическое задание - рассказать о чистых и грязных функциях, в чем их суть, и почему у тебя все таки чистая и в каком случае она может стать грязной в контексте js. Цитировать учебник не надо, будет намного лучше если ты своими словами перескажешь

2022-09-07 20:58 UTC, Shureks-den commented on source/chess.js
> +'use strict';
Классический вопрос - расскажи для чего эта строка

2022-09-07 20:58 UTC, Shureks-den commented on source/chess.js
> +    if ( !Number.isInteger( size ) ) {
Код стайл с отступами скобок разный, давай не делать отступы по краям `(!Number.isInteger(size))`

2022-09-07 20:58 UTC, Shureks-den commented on source/chess.js
> +}
Нет отступа в конце файла :(

2022-09-07 20:58 UTC, Shureks-den commented on source/chess.js
> +    for (let i = 0; i < size; i++) {
Алгоритм какой то слишком похожий на плюсы получается, плюс есть по памяти потенциальная проблема, которая связана с типами данных - так что еще теоретический вопрос. Какие есть типы в js и почему здесь есть 'проблема'
И давай попробуем заменить циклы на методы строк - мне кажется repeat и padStart, padEnd могут в этом помочь

2022-09-07 20:58 UTC, Shureks-den commented on source/chess.js
> +const chess = size => {
Вижу что ты задал функцию как стрелочную, а какие еще способы и в чем между ними разница

2022-09-09 05:07 UTC, Loen15 commented on source/chess.js
> +    size = Number( size );
чистая функция в отличие от грязной не взаимодействует с внешними данными и сохраняет результат при одинаковых входных данных.
Так как в моем случае в функцию передается значение, то я  не меняю ничего из внешних данных => функция чистая
Если бы я передавал объект и в нем что-то менял, то  значения объекта менялись бы и снаружи => функция грязная

2022-09-09 05:11 UTC, Loen15 commented on source/chess.js
> +'use strict';
включает строгий режим, при котором ошибки в коде ведут к выбрасыванию исключений (если исключения не обрабатываются, то программа стопится)

2022-09-09 08:04 UTC, Loen15 commented on source/chess.js
> +const chess = size => {
стандартная функция, функциональные выражения и стрелочная функция
между первыми двумя отличие в том, что 1ая объявляется отдельно, когда 2ая является частью выражения
И в отличие от первых 2  у стрелочной функции this не используется

2022-09-10 09:36 UTC, Shureks-den requested changes

2022-09-10 09:36 UTC, Shureks-den commented on source/chess.js
> +    let n = Number(size);
Переменную n, ты нигде больше не изменяешь, используй const в таком случае. И давай назовем как нибудь по другому, чтобы показать, что мы скастили size к числу

2022-09-10 09:36 UTC, Shureks-den commented on source/chess.js
> +    if (size < 2) {
Наверно надо n проверять

2022-09-10 09:36 UTC, Shureks-den commented on source/chess.js
> +    let evenLine = ''.padStart(n, '* ') + '\n';
Можешь сразу к '\n' делать padStart, с размером n+1

2022-09-10 09:36 UTC, Shureks-den commented on source/chess.js
> +    for (let i = 0; i < n; i++) {
Давай уберем и этот цикл, сделаем переменную с evenLine+oddLine, и вызовем repeat n/2 + прибавляя нечетную строку если n % 2 !== 0

2022-09-14 15:17 UTC, Shureks-den requested changes

2022-09-14 15:17 UTC, Shureks-den commented on source/chess.js
> +    let chessBoard = chessLine.repeat(numericSize / 2) + evenLine.repeat(numericSize % 2);
Все эти переменные можно сделать const, ты же их не меняешь дальше, а вместо chess board можно сразу сделать return

2022-09-14 18:35 UTC, Shureks-den approved these changes

2022-09-14 21:41 UTC, Betchika99 commented
ДЗ принято

2022-09-14 21:41 UTC, closed without merging