Козлов Владимир (Вариант 10)
frontend-park-mail-ru/homework_2022_2 pull request #16
Opened 2022-09-07 15:39 UTC by FackOff25

2022-09-07 21:24 UTC, Victorius19 requested changes
Привет! Поздравляю с успешным завершением первого сема!) Меня зовут Витя, буду проверять твое первое дз.
Неплохое решение, однако оставил несколько комментиков. Если будут какие-то вопросы или не захочешь ждать, пока я чекну гитхаб или почту, то пиши в [телегу](https://t.me/victorius19)

2022-09-07 21:24 UTC, Victorius19 commented on source/letters.js
> +    return arr.join('');
Давай лучше без сделаем без объявления доп переменной? Просто два return с условием. Думаю так код станет проще

2022-09-07 21:24 UTC, Victorius19 commented on source/letters.js
> +function letters(string, bool = null){
Давай добавим проверку на невалидные данные

2022-09-08 09:53 UTC, FackOff25 commented on source/letters.js
> +/**
Заставляет скрипт работать по современным стандартам. Честно говоря изначально собирался создать класс и тогда бы строгий режим включился автоматически, но при написании понял, что в них нет нужды, а про директиву забыл

2022-09-08 10:04 UTC, FackOff25 commented on source/letters.js
> +function letters(string, bool = null){
> Часто вместо function declaration лучше использовать arrow function. Скажи, пожалуйста, в чем разница?

В стрелочные можно пробрасывать this и arguement, т.к. у них самих их нет

2022-09-08 18:13 UTC, Victorius19 commented on source/letters.js
> +/**
Верно. Доп вопрос: строгий режим включен в консоли браузера?)

2022-09-08 18:43 UTC, Victorius19 requested changes
Так гораздо лучше, но надо еще поправить :)

2022-09-08 18:43 UTC, Victorius19 commented on source/letters.js
> +"use strict";
Давай будем везде использовать одинарные ковычки, так код будет выглядеть лучше

2022-09-08 18:43 UTC, Victorius19 commented on source/letters.js
> +let letters = (lettersString, mode = null) => {
Лучше const

2022-09-08 18:43 UTC, Victorius19 commented on source/letters.js
> +    if (typeof lettersString != "string") throw new TypeError('first argument must be string');
А что если я создам строку объект?) Твоя проверка сломается, почитай об этом [тут](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#string_primitives_and_string_objects)
Давай добавим в условие проверку на тип объекта

2022-09-08 18:43 UTC, Victorius19 commented on source/letters.js
> +    if (typeof lettersString != "string") throw new TypeError('first argument must be string');
Кстати, используй !==

2022-09-08 18:43 UTC, Victorius19 commented on source/letters.js
> +        let extraSet = new Set();
 let все еще на месте

2022-09-08 18:43 UTC, Victorius19 commented on source/letters.js
> +        return Array.from(set).join('');
В js коде очень любят краткость. Расскажи, пожалуйста, что такое Spread syntax? И давай тогда сразу используем его чтобы сделать из сета массив

2022-09-08 18:43 UTC, Victorius19 commented on source/letters.js
> +    return (mode ? Array.from(set) : Array.from(set).reverse()).join('')
Хоть в js можно и не писать ; , лучше всегда делать это)

2022-09-08 18:43 UTC, Victorius19 commented on tests/letters.js
> +});
Давай добавим проверки на неверные входные данные и на строку объект (new String('...'))

2022-09-09 07:16 UTC, FackOff25 commented on source/letters.js
> +/**
Изначально нет, но можно включить

2022-09-09 08:44 UTC, FackOff25 commented on source/letters.js
> +        return Array.from(set).join('');
Как я понял это позволяет делать из элемента элементы массива, если это предполагается, и , например, вставить все элементы контейнера в другой контейнер, как бы буквально разделяя (spread) их

2022-09-09 11:35 UTC, Victorius19 requested changes
Уже все хорошо, остались последние правки :)

2022-09-09 11:35 UTC, Victorius19 commented on source/letters.js
> +
После JSDoc не должно быть пропуска строки. Функция должна идти сразу на следующей

2022-09-09 11:35 UTC, Victorius19 commented on source/letters.js
> +        return Array.from(set).join('');
Кстати, давай тут тоже сделаем [...set]

2022-09-09 11:35 UTC, Victorius19 commented on source/letters.js
> +    const set = mode ? new Set(lettersString) : new Set(lettersString.split('').reverse().join(''));
Давай вынесем new Set вне, чтобы он был только один, а условный оператор будем использовать внутри Set(...).

Также если уж использовать спред, то везде :) Давай будем превращать строку в массив им.

И последнее: Set можно инициализировать массивом, так что убери .join(''), он тут не требуется.

2022-09-09 11:35 UTC, Victorius19 commented on source/letters.js
> +        }
Давай добавим тут пропуск строки

2022-09-09 14:47 UTC, Victorius19 requested changes
Уже почти все)

2022-09-09 14:47 UTC, Victorius19 commented on source/letters.js
> +*/
тут нужен в начале всех строчек пробел перед *

2022-09-09 14:47 UTC, Victorius19 commented on source/letters.js
> +    };
Тут не принято ставить ;

2022-09-09 14:47 UTC, Victorius19 commented on source/letters.js
> +    };
Тут тоже не нужна ;

2022-09-10 22:21 UTC, Betchika99 commented
ДЗ принято

2022-09-10 22:21 UTC, closed without merging