Неумоин Дмитрий (Вариант 1)
frontend-park-mail-ru/homework_2022_2 pull request #18
Opened 2022-09-07 22:26 UTC by p1xelse

2022-09-09 07:43 UTC, somebody-kseny requested changes
Доброе утро!)
Меня зовут Ксеня
Поздравляю с переходом на 2й семестр тп и началом учебы)

Спасибо, хорошая аккуратная работа и заранее - ставлю  лайк. Но без исправлений не обойдется. Пиши если что в телегу не стесняйся @somebody_kseny

2022-09-09 07:43 UTC, somebody-kseny commented on tests/zip.js
> +	function _zip_err() {
Кажется незачем выносить функцию отдельно. Можно посто вызвать `zip` в тесте

2022-09-09 07:43 UTC, somebody-kseny commented on tests/zip.js
> +		assert.throws(_zip_err)
`throws` может также проверять, какая именно ошибка выбросилась. Особенно это будет полезно когда ты допишешь проверку, в которой логично будет выбрасывать`TypeError` ([типы ошибок js](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error#error_types))

2022-09-09 07:43 UTC, somebody-kseny commented on source/zip.js
> +    if (args.length == 0) {
Если требуется сравнение, на практике стоит использовать строгое равенство: `===`
[Воть тут](https://developer.mozilla.org/ru/docs/Web/JavaScript/Equality_comparisons_and_sameness) описана разница между == и ===

2022-09-09 07:43 UTC, somebody-kseny commented on source/zip.js
> +    let newObj = {}
Относится ко всему дз:
* В конце строк нужны `;`, прочти пожалуйста [тут](https://learn.javascript.ru/structure#semicolon) - в большинстве случаев работает и без них, но бывают исключения, поэтому проще всегда расставлять
* Вцелом стиль кода: тебе не хватает пробелов между строками. Вот [тут](https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda) несколько гайдов, трудулюбивый вариант - ознакомиться с каким-нибудь из них и привести свой код к нему

2022-09-09 07:43 UTC, somebody-kseny commented on source/zip.js
> +    for (let arg of args) {
В js очень много полезных встроенных методов массивов (и строк, и не только) - [вот тут](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array) слева можно все посмотреть
Перебор в цикле массива очень редко бывает правда небходим - здесь не тот случай. Обрати внимание на метод [reduce](https://learn.javascript.ru/array-methods#reduce-reduceright)

2022-09-09 07:43 UTC, somebody-kseny commented on source/zip.js
> + * @param {object} args - объекты
Не совсем попал в формат документации.
* Object с большой буквы - это обязательно, потому что так называется тип в js.
* У тебя больше одного объекта может быть - это прописывается: [документация](https://jsdoc.app/tags-type.html#:~:text=function%20accepts%20a-,variable%20number,-of%20numeric%20parameters)
* Пустой объект не перестает быть объектом, и такой записи как у тебя на 5 строке вроде нет
* Тип ошибки тоже стоит дописать потом
* `@example` кажется тоже чуть по-другому записывается, проверь пожалуйста по документации

2022-09-10 14:57 UTC, somebody-kseny commented on source/zip.js
> +const zip = (...args) => {
Чем стрелочные функции отличаются от обычных?

2022-09-10 14:59 UTC, somebody-kseny commented on source/zip.js
> +    let newObj = {}
точки с запятой в конце строк забыл добавить 👀

2022-09-10 15:42 UTC, p1xelse commented on source/zip.js
> +'use strict';
`use strict` включает строгий режим, то есть интерпритатор будет явно выбрасывать ошибки, которые раньше мог пропустить, то есть код будет более безопасным.

Если в проге много классов писать его не обязательно.

2022-09-10 15:49 UTC, p1xelse commented on source/zip.js
> +const zip = (...args) => {
- в целом выглядят лаконичнее
- у них нет `this`
- нет связывания .bind(this)
- нельзя юзать с new

2022-09-10 18:27 UTC, somebody-kseny commented on source/zip.js
> +'use strict';
> Если в проге много классов писать его не обязательно.

Не совсем поняла тебя - в общем-то писать ее не надо, если в коде используются модули из ECMAScript 2015 - он тогда автоматически включается

2022-09-11 06:31 UTC, somebody-kseny reviewed
Молодец что догадался про null, осталось чуть-чуть 🤞

2022-09-11 06:31 UTC, somebody-kseny commented on source/zip.js
> +        if (curValue === null) {
Кажется незачем добавлять отдельный тип ошибки. Просто изменить условие в if

2022-09-11 06:31 UTC, somebody-kseny commented on source/zip.js
> +        return Object.keys(curValue).reduce((_accumulator, key) => {
reduce это конечно хорошо, но кажется что один в другом это уже плохо читается. Да и лишние накладные расходы.
У тебя было хорошо в прошлый раз, только вместо цикла `for` есть метод массива `forEach`

2022-09-11 06:33 UTC, somebody-kseny commented on tests/zip.js
> +	QUnit.test('Функция бросает исключение, если нет аргументов', function (assert) {
`;` пожалуйста
и на 29 строке лишний отступ, сдавать с таким было бы нельзя: стиль кода - страшная вещь

2022-09-12 07:15 UTC, somebody-kseny reviewed
Все-таки прошу еще улучшений

2022-09-12 07:15 UTC, somebody-kseny commented on source/zip.js
> +        if (typeof curValue !== "object" || curValue === null) {
Тут есть вопросы, определение типа это всегда сложно в js)
1. Массив тоже определится как объект - это нужно исправить, давай и в тест добавим массив
2. Сложновато читается строка, особенно сейчас ее еще увеличить нужно будет - кажется что `&& curValue !== null` чуть лучше
3. (со звездочкой)) Чтобы совсем все запутать, в js есть возможность вызвать конструктор примитивного типа,  и `typeof new Boolean(true) === 'object';`
Сможешь догадаться, как и такие аргументы отловить?
Подсказка. Посмотри в сторону методов объекта Object, который является прототипом (если переводить - родительским классом) всего что есть в javascript

2022-09-12 21:16 UTC, Betchika99 commented
ДЗ принято, но на всякий случай подскажу на будущее - во фронтенд-проектах используются одинарные кавычки обычно :)

2022-09-12 21:16 UTC, closed without merging