var-7 done: plain.js release, jsdoc done, some tests added
frontend-park-mail-ru/homework_2022_2 pull request #19
Opened 2022-09-08 08:04 UTC by george007361

Автор: Георгий Илларионов 7 вариант

2022-09-08 19:31 UTC, Victorius19 requested changes
Привет! Поздравляю с окончанием первого семестра!)
Меня зовут Витя, я буду проверять твое дз0.
Интересное решение, но есть замечания. Если будут какие-то вопросы или не захочешь ждать, пока я чекну гитхаб или почту, то пиши в [телегу](https://t.me/victorius19)

2022-09-08 19:31 UTC, Victorius19 commented on source/plain.js
> +'use strict';
Хорошо, что ты используешь строгий режим! Кстати, расскажи, пожалуйста, зачем он нужен?

2022-09-08 19:31 UTC, Victorius19 commented on source/plain.js
> +function plain(srcArray) {
Часто вместо function declaration лучше использовать arrow function. Скажи в чем разница?

2022-09-08 19:31 UTC, Victorius19 commented on source/plain.js
> +    let resArr = [];
Для массивов лучше использовать const. Они хранятся ссылками, поэтому мы изменяем содержимое ссылки, а не её саму.

2022-09-08 19:31 UTC, Victorius19 commented on source/plain.js
> +}
В конце всех файлов лучше добавлять один дополнительный перенос строки. ([почему это нужно](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline/729795#729795))

2022-09-08 19:31 UTC, Victorius19 commented on source/plain.js
> +    }
Когда есть некая переменная, которая используется на каждой итерации в цикла в JS очень удобно использовать функцию [reduce()](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce), почитай про нее, с ней получится сделать все очень красиво и в и "одну строчку" (как любят все жсеры:) )

Однако главная проблема такого алгоритма - рекурсия. Если в твою функцию передать массив с очень большой вложенностью, то все сломается, т.к. в рекурсии каждая следующая вложенность массива будет заполнять стек вызовов и когда-то он закончится.

Но есть и хорошая новость: любую рекурсию можно реализовать циклом. Давай сделаем это

2022-09-09 19:19 UTC, george007361 commented on doc/fonts/OpenSans-Bold-webfont.svg
> +<?xml version="1.0" standalone="no"?>
Ок, думал отчет jsdoc надо было сгенерировать)

2022-09-09 19:21 UTC, george007361 commented on source/plain.js
> +'use strict';
Убирает ошибки прошлых версий движка, убирает обратную совместимость со старыми врсиями

2022-09-09 19:25 UTC, george007361 commented on source/plain.js
> +    let resArr = [];
Поправлю, спасибо!

2022-09-09 19:32 UTC, george007361 commented on source/plain.js
> +function plain(srcArray) {
А, еще func decl не во время выполнения скрипта определяют функцию, а стрелочные во время

2022-09-09 20:40 UTC, george007361 commented on source/plain.js
> +    }
Сделал через "стек" без рекурсии

2022-09-09 20:40 UTC, george007361 commented on source/plain.js
> +}
+

2022-09-10 17:32 UTC, Victorius19 commented on source/plain.js
> +'use strict';
В целом так. Скажи, а в консоли браузера строгий режим?

2022-09-10 17:37 UTC, Victorius19 commented on source/plain.js
> +function plain(srcArray) {
Да, у стрелочных функций нет своего this. Давай используем тут стрелочную функцию

2022-09-10 18:09 UTC, Victorius19 requested changes
Хорошее решение! Остались минимальные правки

2022-09-10 18:09 UTC, Victorius19 commented on source/plain.js
> +    const stack = srcArray.slice();
Очень круто, что ты не ломаешь входной массив и копируешь его)

Давай еще добавим проверку на невалидные входные данные?

2022-09-10 18:09 UTC, Victorius19 commented on source/plain.js
> +        }
Лучше убрать перенос строки

2022-09-10 18:09 UTC, Victorius19 commented on source/plain.js
> +        const elem = stack.pop();
Я уже сильно придираюсь, но тут лучше добавить перенос строки :)

2022-09-10 18:09 UTC, Victorius19 commented on tests/plain.js
>  QUnit.module('Тестируем функцию plain', function () {
Давай добавим в тест проверку на невалидные входные данные (если передаем не массив)

2022-09-10 18:09 UTC, Victorius19 commented on source/plain.js
> +            stack.push(...elem.slice());
slice() тут лишний массив, спред оператор сам "скопирует" массив ([ссылочка](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#:~:text=more%20than%20once.-,Copy%20an%20array,-const%20arr%20%3D))

2022-09-10 19:57 UTC, george007361 commented on source/plain.js
> +'use strict';
Нет, но его можно включить той же командой

2022-09-11 18:52 UTC, Betchika99 commented
ДЗ принято

2022-09-11 18:52 UTC, closed without merging