Вариант 12, Костев Дмитрий
frontend-park-mail-ru/homework_2022_2 pull request #2
Opened 2022-09-04 16:46 UTC by LDK28

2022-09-05 20:07 UTC, somebody-kseny commented
Привет! Меня зовут Ксеня. Как ты догадался буду проверять твое дз)
Молодец что оперативно сделал - однако все же нужны будут правки. Сейчас оставлю комментарии
Если что, можешь спокойно писать в телеграм @somebody_kseny

2022-09-05 20:15 UTC, somebody-kseny commented
Первое - что-то пошло не так с гитом. Это касается двух файлов, где ты добавил строки, а гит воспринимает их как замененные полностью. **Пока в ветке работаешь только ты**, стоит воспользоваться возможностями гита по перезаписи истории и сделать все красиво.
Скорее всего понадобятся команды:
https://git-scm.com/docs/git-reset#Documentation/git-reset.txt---soft
https://git-scm.com/docs/git-push#Documentation/git-push.txt---force

2022-09-05 21:28 UTC, LDK28 commented
> Первое - что-то пошло не так с гитом. Я имею в виду файлы index.html и tests/minmax.js .Ты добавил в них строки, а гит воспринимает их как замененные полностью. (Пока в ветке работаешь только ты) стоит воспользоваться возможностями гита по перезаписи истории и сделать все красиво. Скорее всего понадобятся команды: https://git-scm.com/docs/git-reset#Documentation/git-reset.txt---soft https://git-scm.com/docs/git-push#Documentation/git-push.txt---force

Ксения, Здравствуйте! 
Исправил ошибку с гитом. Но во время исправлений пришлось запушить исходную версию, так как гит не давал исправить локально, все равно писал о полном изменении файла. По итогу менял файлы прям на сайте. 
Можно ли как-то переоткрыть  PR или создавать новый?

2022-09-06 07:07 UTC, somebody-kseny requested changes

2022-09-06 07:07 UTC, somebody-kseny commented on source/minmax.js
> +    const arrayOfNumbers = numbers.map(v => +v);
Реализация на мой взгляд достаточно хороша.
Но давай ее более в стиле js сделаем.
Вместо отдельно 9 строки и отдельного массива можно это преобразование перенести на 5 строку, используя синтаксический сахар js. Больше не скажу, если не догадаешься пиши.

2022-09-06 07:07 UTC, somebody-kseny commented on source/minmax.js
> +    if (numbers === null) {
Также вместо такой проверки можно использовать оператор `?` в строке с `return`

2022-09-06 07:32 UTC, LDK28 commented on source/minmax.js
> +'use strict'
Для строгого использования es5 и более новых стандартов в коде(современного JS).

2022-09-06 07:34 UTC, somebody-kseny commented
Последний момент: теперь давай пожалуйста работать с гитом как положено, только добавлять коммиты и не через интерфейс github-а. Так же, если зайдешь в тупик - пиши, но вообще гугли)
Ты молодец, удачи 🤞

2022-09-06 07:37 UTC, LDK28 commented on source/minmax.js
> +const minmax = (string) => {
С помощью ключевого слова 'function'. В отличие от классических функций стрелочные не имеют this и arguments, не могут быть вызваны с new.

2022-09-06 08:43 UTC, LDK28 commented on tests/minmax.js
> +	QUnit.test('Парочка дополнительных тестов :)', function (assert) {
Исправил тесты, добавил в каждое тестирование по одному примеру.

2022-09-06 08:43 UTC, LDK28 commented on source/minmax.js
> +const minmax = (string) => {
Поменял на stringWithNumbers.

2022-09-06 08:44 UTC, LDK28 commented on source/minmax.js
> +const minmax = (string) => {
Добавил проверку типа и проброс Exception.

2022-09-06 08:44 UTC, LDK28 commented on source/minmax.js
> +
Описал.

2022-09-06 08:45 UTC, LDK28 commented on source/minmax.js
> +    const arrayOfNumbers = numbers.map(v => +v);
Сжал всё в одну строку.

2022-09-06 08:45 UTC, LDK28 commented on source/minmax.js
> +    if (numbers === null) {
Заменил if на return с тернарным оператором

2022-09-07 17:36 UTC, somebody-kseny requested changes
Спасибо, стало лучше)
Однако придется еще подшлифовать

2022-09-07 17:36 UTC, somebody-kseny commented on tests/minmax.js
>  });
Лучше все же допиши отдельный тест (или парочку) в дополнение к тому что сейчас. Логично кажется будет проверить выбрасывание исключения.

2022-09-07 17:36 UTC, somebody-kseny commented on source/minmax.js
> +    return (numbers === undefined ? [undefined, undefined] : [Math.min(...numbers), Math.max(...numbers)]);
`numbers === undefined` конечно работает, но более универсально использовать просто проверку на отрицание - `!` (Вот так вот оно, то вопросительные знаки то отрицательные)
Это для справки

Здесь же проще инвертировать условие и избежать отрицания вобще, сделай пожалуйста

2022-09-07 17:36 UTC, somebody-kseny commented on source/minmax.js
> + */
Формат JSdoc - это не просто текстровый комментарий) Гуглится легко. Ипользуй его по максимуму пожалуйста.
В том числе нужно описать твое исключение.

2022-09-07 17:36 UTC, somebody-kseny commented on source/minmax.js
> +    const numbers = stringWithNumbers.match(regularExpression)?.map(v => +v);
Мне сразу не понравился опеатор +. Это может немного вкусовщина, но он не дает мне покоя. Замени пожалуйста например на `Number()`, чтобы читалось лучше. "Интересное по теме": https://stackoverflow.com/a/17106702

Кстати открой тайну, почему `v` в стрелочной функции?) Идеально было бы заменить на что-нибудь вроде `str`

2022-09-07 17:36 UTC, somebody-kseny commented on source/minmax.js
> +    const numbers = stringWithNumbers.match(regularExpression)?.map(v => +v);
Кажется мне стоило написать это сразу когда в прошлый раз смотрела, извини, сама учусь)

2022-09-07 18:20 UTC, LDK28 commented on tests/minmax.js
>  });
Дописал тесты, где аргумент - число, массив или объект.

2022-09-07 18:21 UTC, LDK28 commented on source/minmax.js
> +    return (numbers === undefined ? [undefined, undefined] : [Math.min(...numbers), Math.max(...numbers)]);
Исправил

2022-09-07 18:21 UTC, LDK28 commented on source/minmax.js
> + */
Добавил описание аргумента, возвращаемого значения и ошибки.

2022-09-07 18:23 UTC, LDK28 commented on source/minmax.js
> +    const numbers = stringWithNumbers.match(regularExpression)?.map(v => +v);
Заменил + на `Number()`. `v` было от variable, но уже понял, что некорректно так называть. Исправил на `item`.

2022-09-08 05:47 UTC, somebody-kseny reviewed
Привет)
Надеюсь что последние небольшие исправления
Некоторые из замечаний можно было выдать раньше, спасибо за терпение)

2022-09-08 05:47 UTC, somebody-kseny commented on tests/minmax.js
>  });
Вместо того, чтобы три раза создавать ошибку, можно один раз создать ее и записать в константу

2022-09-08 05:47 UTC, somebody-kseny commented on source/minmax.js
> +        throw new Error('INVALID_ARGUMENT_TYPE');
Лучше заменить просто Error на TypeError, это более конкретно: [ссылочка](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error#:~:text=%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8%20eval().-,TypeError,-%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D1%91%D1%82%20%D1%8D%D0%BA%D0%B7%D0%B5%D0%BC%D0%BF%D0%BB%D1%8F%D1%80%2C%20%D0%BF%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D1%8F%D1%8E%D1%89%D0%B8%D0%B9)

Причем сообщение тогда можно сделать более информативным, на тему что ожидалась строка

2022-09-08 05:47 UTC, somebody-kseny commented on source/minmax.js
> + */
Насколько понимаю, в `{}` к throws должен быть тип, то есть `TypeError`

2022-09-08 05:47 UTC, somebody-kseny commented on source/minmax.js
> +    return (numbers ? [Math.min(...numbers), Math.max(...numbers)] : [undefined, undefined]);
Внешние круглые скобочки лишние, только усложняют чтение

2022-09-08 05:47 UTC, somebody-kseny commented
Если что не обязательно отмечать на каждый комментарий)

2022-09-08 05:54 UTC, somebody-kseny commented
В js doc в `@throws` нужно записать тип ошибки, кажется что это `TypeError`
Можешь сам еще повнимательнее почитать про формат, проверить

2022-09-08 05:55 UTC, somebody-kseny commented on source/minmax.js
> +const minmax = (string) => {
Хорошо)

2022-09-08 06:03 UTC, somebody-kseny commented on source/minmax.js
> +'use strict'
Может быть не поняла тебя, но кажется не так. Строгий режим введен с es5 стандарта и нужен для более строгого использования javascript, уменьшает количество неявного поведения.
Конечно же [ссылка](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Strict_mode) :)

2022-09-08 07:15 UTC, LDK28 commented
Исправил последние замечания.

2022-09-08 17:05 UTC, somebody-kseny commented on tests/minmax.js
> +		console.log(typeof error);
Будем считать что я этого не видела.

К слову, напоминаю о существовании линтеров (автоматическая проверка стиля кода, там и о консоль-логах предупреждение можно включить), ссылка по теме: https://learn.javascript.ru/coding-style#avtomatizirovannye-sredstva-proverki-lintery

В проекте потом нужно будет их настроить, сейчас конечно излишне

2022-09-08 17:11 UTC, LDK28 commented on tests/minmax.js
> +		console.log(typeof error);
Лог был удалён

2022-09-10 21:58 UTC, Betchika99 commented
ДЗ принято

2022-09-10 21:58 UTC, closed without merging