hw0
frontend-park-mail-ru/homework_2022_2 pull request #20
Opened 2022-09-08 19:09 UTC by EuphoriaAbsorber

Колесников Артём Вариант 11

2022-09-08 19:30 UTC, DPeshkoff commented on source/rle.js
> + * @returns {string} ansString - RLE сжатая строка.
Круто, что ты написал JSDoc! Давай добавим еще пример использования?

2022-09-08 19:31 UTC, DPeshkoff commented on source/rle.js
> +const rle = (str) => {
Классно, ты используешь стрелочные функции - это правильный подход)

Объясни, пожалуйста, чем они отличаются от обычных?

2022-09-08 19:33 UTC, DPeshkoff commented on source/rle.js
> +  }
Решение рабочее, но чувствуется подход из С++)

В JavaScript есть [много методов](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String) для работы со строками, которые могут здесь существвнно упростить код)

2022-09-08 19:36 UTC, DPeshkoff commented on source/rle.js
> +  }
Кажется, для проверки входного параметра этого недостаточно - а вдруг это не строка? Вдруг это массив или вообще Date?

2022-09-08 19:37 UTC, DPeshkoff commented on tests/rle.js
> +		assert.strictEqual(rle(null), 'Incorrect object');
Вместо возврата Incorrect string / object лучше выбрасывать ошибку - JS умеет это делать из коробки

2022-09-08 19:37 UTC, DPeshkoff commented on tests/rle.js
> +	});
А если на вход будет передано кое-что поинтереснее? Infinity, NaN, Array?

2022-09-09 07:46 UTC, EuphoriaAbsorber commented on source/rle.js
> +const rle = (str) => {
1. Не имеют this
2. Чуть короче синтаксис

2022-09-09 11:49 UTC, DPeshkoff requested changes

2022-09-09 11:49 UTC, DPeshkoff commented on source/rle.js
> +  }
Давай заменим этот цикл на [кое-что получше](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce))

2022-09-09 22:01 UTC, DPeshkoff requested changes

2022-09-09 22:01 UTC, DPeshkoff commented on source/rle.js
> +  if (typeof str !== 'string') {
Строки могут быть и объектами)
<img width="657" alt="Снимок экрана 2022-09-10 в 1 00 41" src="https://user-images.githubusercontent.com/31134795/189451617-f98bff7e-0179-4c43-a652-f99f32df9c10.png">

2022-09-11 21:30 UTC, DPeshkoff requested changes

2022-09-11 21:30 UTC, DPeshkoff commented on source/rle.js
> +    if(!(str instanceof String)){
Можно объединить if'ы

2022-09-11 21:30 UTC, DPeshkoff commented on source/rle.js
> +  let ansString = arrFromString.reduce((ansString, curSymb) => {
Давай добавим пустых строк между блоками, чтобы было проще читать (особенно тут, но добавить лучше по всей функции)

2022-09-11 21:30 UTC, DPeshkoff commented on source/rle.js
> +    throw new Error("Incorrect string");
Да это тоже может TypeError быть)

2022-09-13 19:17 UTC, DPeshkoff approved these changes

2022-09-14 15:28 UTC, Betchika99 commented
ДЗ принято

2022-09-14 15:28 UTC, closed without merging