dz0 done
frontend-park-mail-ru/homework_2022_2 pull request #22
Opened 2022-09-08 23:04 UTC by thelvv

Федоров Александр

2022-09-09 15:11 UTC, DPeshkoff requested changes

2022-09-09 15:11 UTC, DPeshkoff commented on source/tree.js
> +    }
Решение хорошее, но что если попробовать избавиться от этого цикла? Сюда прям [напрашивается](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce))

2022-09-09 15:11 UTC, DPeshkoff commented on source/tree.js
> +}
Давай добавим перенос строки в конце файла ([почему это важно](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline/729795#729795))

2022-09-09 15:11 UTC, DPeshkoff commented on tests/tree.js
> +        assert.strictEqual(tree(1), null);
Не стоит изменять отступы в оригинальных тестах - так тяжелее смотреть различие в коде)

2022-09-09 15:11 UTC, DPeshkoff commented on tests/tree.js
> +
Можно добавить еще больше проверок некорректного параметра - высоты NaN, отрицательной и тому подобное)

2022-09-09 15:11 UTC, DPeshkoff commented
Привет!
Поздравляю с переходом на второй семестр и добро пожаловать на курс фронтенд-разработки)
Решение неплохое, но нужно кое-что исправить - оставил несколько комментариев. Если возникнут какие-то вопросы, можешь писать здесь или в [Телеграм](https://t.me/DmPesh))

2022-09-10 17:46 UTC, DPeshkoff requested changes

2022-09-10 17:46 UTC, DPeshkoff commented on source/tree.js
> +    }
Вот эту часть можно упростить)

2022-09-10 17:46 UTC, DPeshkoff commented on source/tree.js
> +     * @type {numer[]}
```suggestion
     * @type {number[]}
```

2022-09-10 17:46 UTC, DPeshkoff commented on source/tree.js
> +const tree = number => {
Аргумент принято заключать в ()

2022-09-10 17:46 UTC, DPeshkoff commented on source/tree.js
> +    }
можно разнести на несколько разных блоков, чтобы не вызывать каждый раз Number
третья проверка - нужно проверять на NaN тогда уж)

2022-09-10 17:46 UTC, DPeshkoff commented on source/tree.js
> +/**
Лучше новый код создавать в строгом режиме)

2022-09-10 17:46 UTC, DPeshkoff commented on source/tree.js
> +    let answer = NumbersOfLevels.reduce(function (prev, curr) {
внутри reduce тоже можно использовать стрелочные функции)

2022-09-10 17:46 UTC, DPeshkoff commented on tests/tree.js
> +        assert.strictEqual(tree(1), null);
up)

2022-09-10 17:46 UTC, DPeshkoff commented on tests/tree.js
> +
up)

2022-09-11 12:41 UTC, DPeshkoff requested changes

2022-09-11 12:41 UTC, DPeshkoff commented on source/tree.js
> +    number = Number(number);
Сейчас ты изменяешь входной параметр - давай не будем так делать)

2022-09-11 12:41 UTC, DPeshkoff commented on source/tree.js
> +        let indent = ' '.repeat((maxWidth - numOfStars) / 2);
Кажется, что эти две переменные не изменяются

2022-09-11 12:41 UTC, DPeshkoff commented on tests/tree.js
> +        assert.strictEqual(tree(1), null);
up)

2022-09-11 21:34 UTC, DPeshkoff requested changes

2022-09-11 21:34 UTC, DPeshkoff commented on source/tree.js
> +        ((!(Number.isInteger(Number(number)))) || (!(Number.isSafeInteger(Number(number)))))) {
Ты выпилил совсем - и у нас снова Number() вызывается несколько раз)

Давай вынесем это в отдельную переменную/константу, но не будем перезаписывать number

2022-09-11 21:34 UTC, DPeshkoff commented on source/tree.js
> +    let indent = ' '.repeat((maxWidth - 1) / 2);
здесь тоже const

2022-09-12 13:23 UTC, DPeshkoff approved these changes

2022-09-12 21:14 UTC, Betchika99 commented
ДЗ принято

2022-09-12 21:14 UTC, closed without merging