Егоров Аким (вариант 6)
frontend-park-mail-ru/homework_2022_2 pull request #23
Opened 2022-09-09 10:23 UTC by AkimEgorov

2022-09-12 10:26 UTC, Victorius19 requested changes
Хорошо, что ты смог решить эту задачу с помощью генераторов, но есть пару замечаний :)

2022-09-12 10:26 UTC, Victorius19 commented on source/tree.js
> +			'  |  \n'
Перепиши пример, тут лишний отсуп

2022-09-12 10:26 UTC, Victorius19 commented on source/tree.js
> +"use strict";
Хорошо, что ты используешь строгий режим. Расскажи, для чего он используется?

2022-09-12 10:26 UTC, Victorius19 commented on source/tree.js
> +"use strict";
Кстати, давай везде использовать одинарные кавычки

2022-09-12 10:26 UTC, Victorius19 commented on source/tree.js
> + * @returns {String} | {null}
Типы возвращаемых значений пишутся не так. Символ | должен быть внутри фигурных скобок

2022-09-12 10:26 UTC, Victorius19 commented on source/tree.js
> + * @returns {String} | {null}
И еще, как добавишь валидацию входных данных, то возвращаемое значение станет только одним типом

2022-09-12 10:26 UTC, Victorius19 commented on source/tree.js
> +  return string;
Давай перепишем это на reduce. Можно создать массив нужной длинны и обойти его

2022-09-12 13:42 UTC, AkimEgorov commented on source/tree.js
> +"use strict";
Когда появился ECMAScript 5 (ES5) он добавил новые возможности в язык и изменил некоторые из существующих. Чтобы активировать их нужно использовать директиву 'use strict'. Когда включен строгий режим, весь сценарий работает в «современном» режиме.

2022-09-14 17:33 UTC, Victorius19 requested changes
Ух, это было не просто)

2022-09-14 17:33 UTC, Victorius19 commented on source/tree.js
> +function* generateSequence(start, end, element) {
Давай избавимся от переменной старт, ты все равно всегда передаешь сюда 1

2022-09-14 17:33 UTC, Victorius19 commented on source/tree.js
> +function* generateSequence(start, end, element) {
И сделаем итерацию не от 1 до end, а от 0 до end -1

2022-09-14 17:33 UTC, Victorius19 commented on source/tree.js
> +function* generateTree (height, row, element_1, element_2) {
В js не принято называть переменные через нижнее подчеркивание

2022-09-14 17:33 UTC, Victorius19 commented on source/tree.js
> +function* generateTree (height, row, element_1, element_2) {
Давай избавимся от element_1, ты все равно передаешь всегда только одно значение

2022-09-14 17:33 UTC, Victorius19 commented on source/tree.js
> +  yield "\n";
Одиночные кавычки

2022-09-14 17:33 UTC, Victorius19 commented on source/tree.js
> +  }
Давай лучше вместо этих двух циклов сделаем еще одну функцию генератор, в которой будем вызывать уже другой генератор. Сначала в цикле создадим листву, а потом одним вызовом ножку

2022-09-14 17:33 UTC, Victorius19 commented on source/tree.js
> +function* generateTree (height, row, element_1, element_2) {
И давай назовем эту функцию generateLine, чтобы обозначить, что это генерация не всего дерева, а только одной строки

2022-09-14 17:33 UTC, Victorius19 commented on source/tree.js
> +function tree (n) {
Давай сделаем стрелочную функцию. Кстати, расскажи в чем разница между стрелочными и обычными функциями?

2022-09-14 17:33 UTC, Victorius19 commented on source/tree.js
> +
Не очень хорошая проверка на число. Давай не будем возвращать null, а все эти исключение объединим в один иф в котором сделаем проверку на isInteger и isFinite

2022-09-14 17:33 UTC, Victorius19 commented on tests/tree.js
> +
Добавь проверки на NaN, null

2022-09-14 17:33 UTC, Victorius19 commented on source/tree.js
> +
Также не хватает проверок на отрицательные числа

2022-09-14 17:33 UTC, Victorius19 commented on source/tree.js
> +  yield* generateSequence(1, height - 1 - row, element_1);
Давай лучше уберем эти комменты, тем более они не отражают смысл, ведь теперь ты ввел переменную element

2022-09-14 20:25 UTC, AkimEgorov commented on source/tree.js
> +
null просят вернуть самые первые тесты, которые изначально были в задании. Не знаю, могу я их менять или нет

2022-09-14 20:31 UTC, AkimEgorov commented on source/tree.js
> +function tree (n) {
Стрелочные функции обладают простым и лаконичным синтаксисом, который гораздо более удобен, чем у простых функций. Однако они не имеют this, не имеют arguments, не могут быть вызваны с new. Всё это потому, что они предназначены для небольшого кода, который не имеет своего «контекста», выполняясь в текущем

2022-09-14 20:36 UTC, AkimEgorov commented on source/tree.js
> +
Проверку на отрицательные числа автоматически выполняет проверка на значение высоты, которая не должна быть меньше трех))
Тест на отрицательные числа имеется :)

2022-09-14 20:53 UTC, Victorius19 requested changes
Уже близко

2022-09-14 20:53 UTC, Victorius19 commented on source/tree.js
> + */
Перенеси JSDoc непосредственно к функции tree()

2022-09-14 20:53 UTC, Victorius19 commented on source/tree.js
> +  for (let i = 0; i <= end - 1; i++) yield element;
Сделай оператор < и избався от end -1

2022-09-14 20:53 UTC, Victorius19 commented on source/tree.js
> +  yield* generateSequence(height - 1 - row, ' ');
Давай уберем тут пропуски между строками

2022-09-14 20:53 UTC, Victorius19 commented on source/tree.js
> +  yield "\n";
все еще одиночный кавычки

2022-09-14 20:53 UTC, Victorius19 commented on source/tree.js
> +let tree = (n) => {
Используй const для стрелочной функции

2022-09-14 20:53 UTC, Victorius19 commented on source/tree.js
> +}
Давай создадим именно функцию генератор. В ней будет генерировать как листья елочки, так и ногу

2022-09-14 20:53 UTC, Victorius19 commented on source/tree.js
> +  return string;
Давай будем собирать генератор с помощью spread оператора и функции join

2022-09-14 20:53 UTC, Victorius19 commented on source/tree.js
> +  for (let i = 0; i <= end - 1; i++) yield element;
Давай также весь код будем писать с 4, а не с 2 пробелами

2022-09-14 21:21 UTC, Victorius19 approved these changes

2022-09-14 21:49 UTC, Betchika99 commented
ДЗ принято

2022-09-14 21:49 UTC, closed without merging