first upload
frontend-park-mail-ru/homework_2022_2 pull request #24
Opened 2022-09-09 15:45 UTC by VarenytsiaMykhailo

Варениця М, вариант 3

2022-09-11 19:56 UTC, Sarafa2n requested changes
Привет! Добро пожаловать на курс фронтенд разработки.
Ты неплохо справился с дз0, но у меня есть пару замечаний, давай их поправим, если что пиши сюда или в телеграм (sarafa2n)

2022-09-11 19:56 UTC, Sarafa2n commented on source/roman.js
> +'use strict';
А можешь рассказать что эта строка делает ?

2022-09-11 19:56 UTC, Sarafa2n commented on source/roman.js
> +const ROMAN_MAPPING = ["I", "IV", "V", "IX", "X", "XL", "L", "XC", "C", "CD", "D", "CM", "M"];
Давай использовать одинарные ковычки

2022-09-11 19:56 UTC, Sarafa2n commented on source/roman.js
> + * @param {input} input - string of roman or number of arabic.
Давай дополним доку типами и еще примером использования функции

2022-09-11 19:56 UTC, Sarafa2n commented on source/roman.js
> +const roman = input => {
давай пропсы оборабернем в скобки

2022-09-11 19:56 UTC, Sarafa2n commented on source/roman.js
> +    let result;
кажется эта переменная бесполезная, посмотри она по факту не нужна

2022-09-11 19:56 UTC, Sarafa2n commented on source/roman.js
> +    }
Это все можно упросить, посмотри как можно использовать Number, и это получится в одну строку, а проверку регуляркой на то что в строке римские цифры лучше унести в to_arab

2022-09-11 19:56 UTC, Sarafa2n commented on source/roman.js
> +        if (/^[0-9]+$/.test(input) && !input.toString().startsWith('0')) {
Давай регулярки вынесем в константы
`input.toString().startsWith('0')` тут `toString()` не имеет смысла

2022-09-11 19:56 UTC, Sarafa2n commented on source/roman.js
> +        if (/^[0-9]+$/.test(input.toString())) {
а как у тебя могут быть другие символы если передано число ?

2022-09-11 19:56 UTC, Sarafa2n commented on source/roman.js
> +const to_roman = arab => {
Давай использовать camelCase, так в js принято)

2022-09-11 19:56 UTC, Sarafa2n commented on source/roman.js
> +        return "";
👀

2022-09-11 19:56 UTC, Sarafa2n commented on source/roman.js
> +    //console.log(result);
убрать стоит

2022-09-11 19:56 UTC, Sarafa2n commented on source/roman.js
> +const to_arab = roman => {
👀

2022-09-11 19:56 UTC, Sarafa2n commented on source/roman.js
> +        if (text.substr(textStartPos, ROMAN_MAPPING[n].length) === ROMAN_MAPPING[n]) {
лучше substring так как substr упразняется

2022-09-11 19:56 UTC, Sarafa2n commented on source/roman.js
> +    let text = roman.toUpperCase();
const

2022-09-11 19:56 UTC, Sarafa2n commented on source/roman.js
> +    //console.log(result);
👀

2022-09-11 19:56 UTC, Sarafa2n commented on tests/roman.js
> +	});
Давай добавим больше тестов

2022-09-12 01:01 UTC, VarenytsiaMykhailo commented on source/roman.js
> +    let result;
> кажется эта переменная бесполезная, посмотри она по факту не нужна

Нужна. Если она будет неинициализированной (в случае некорректных входных данных), то вернется undefined, как и задумывалось) иначе, в ней будет лежать результат работы функций.

2022-09-12 15:48 UTC, VarenytsiaMykhailo commented on source/roman.js
> +'use strict';
https://learn.javascript.ru/strict-mode

2022-09-13 18:08 UTC, Sarafa2n commented on source/roman.js
> +'use strict';
а своими словами ?

2022-09-13 18:27 UTC, Sarafa2n requested changes

2022-09-13 18:27 UTC, Sarafa2n commented on source/roman.js
> +    const arabicPatter = /^[0-9]+$/;
давай проверять что если тип не строка и не число то выкидывать исключение

2022-09-13 18:27 UTC, Sarafa2n commented on source/roman.js
> +    const arabicPatter = /^[0-9]+$/;
у тебя дубликация этой регулярки

2022-09-13 18:27 UTC, Sarafa2n commented on source/roman.js
> +    if (arabicPatter.test(input) && !input.toString().startsWith('0')) {
Я же писал про то что можно использовать Number, это здорово что ты можешь регуляркой, но давай попробуем все таки сделать как я описал

2022-09-13 18:27 UTC, Sarafa2n commented on source/roman.js
> +        return undefined;
давай тут исключение кидать

2022-09-13 18:44 UTC, VarenytsiaMykhailo commented on source/roman.js
> +'use strict';
> а своими словами ?

Отключает совместимость с старыми версиями JS и позволяет писать используя последние стандарты и использовать современные фичи, некоторые из которых, в старых стандартах могли работать по другому

2022-09-14 21:32 UTC, Sarafa2n requested changes

2022-09-15 09:08 UTC, Sarafa2n requested changes

2022-09-15 09:08 UTC, Sarafa2n commented on source/roman.js
> +        }();
А что так сложно ? Не проще ли это сделать выше, не мешать логику работы с обработкой типов
И зачем все оборачивать вызов throw в функцию?

2022-09-15 09:08 UTC, Sarafa2n commented on source/roman.js
> +        throw TypeError('Incorrect input data.');
Давай писать конкретно, что такая-то функция принимает в себя только такие типы, а то у тебя одна ошибка на 3 функции

2022-09-15 09:08 UTC, Sarafa2n commented on tests/roman.js
> +
Давай добавим больше хороших тестов

2022-09-15 14:24 UTC, Sarafa2n requested changes

2022-09-15 14:24 UTC, Sarafa2n commented on source/roman.js
> +    if (!(isInteger || (typeof input === 'string' || input instanceof String))) {
одни лишние скобки в if есть

2022-09-16 17:21 UTC, Betchika99 commented
ДЗ принято

2022-09-16 17:21 UTC, closed without merging