Макаров А Вариант 16
frontend-park-mail-ru/homework_2022_2 pull request #25
Opened 2022-09-10 20:57 UTC by Aralary

done

2022-09-11 17:58 UTC, Shureks-den commented
Привет, меня зовут Саша, я буду проверять твое дз и вместе мы сделаем его лучше :). По всем вопросам и с просьбами проверить еще раз можешь писать в тг https://t.me/alexklonov

2022-09-11 18:13 UTC, Shureks-den requested changes

2022-09-11 18:13 UTC, Shureks-den commented on source/format.js
> +function maxColWidth(numbers, col, colsNumber) {
Эту функцию можно убрать, посмотри в сторону функции Math.max, преобразования элементов через Array.map и spread (...) синтаксиса

2022-09-11 18:13 UTC, Shureks-den commented on source/format.js
> +function format(numbers, cols) {
Давай использовать синтаксис стрелочных функций. Также расскажи в чем разница между этими двумя синтаксисами

2022-09-11 18:13 UTC, Shureks-den commented on source/format.js
> +            if (j < cols - 1 && numbers[i + j] !== numbers[numbers.length - 1]) {
Это конструкцию можно заменить на тернарный оператор cond ? ifTrue : ifFalse

2022-09-11 18:13 UTC, Shureks-den commented on source/format.js
> +            let colWidth = maxColWidth(numbers, j, cols);
Для переменных, которые не изменяешь в блоке юзай const.

2022-09-11 18:13 UTC, Shureks-den commented on source/format.js
> +            }
Вот эти строки можешь заменить через String.repeat

2022-09-11 18:13 UTC, Shureks-den commented on source/format.js
> +        for (let j = 0; (j < cols) && (i + j < numbers.length); ++j) {
Какая то очень сложная логика, особенно с вложенным циклом, может есть методы массива, которые помогут?

2022-09-11 18:13 UTC, Shureks-den commented on source/format.js
> +
Еще **нужно** добавить свои тесты, в том числе и негативные. Так что давай добавим проверки некорректных данных, например если в массиве есть строки, и будем бросать ошибки, добавив на это тесты.
Также можно учесть кейс вроде `format([1,2,3], 4)`

2022-09-11 18:13 UTC, Shureks-den commented on source/format.js
> +            let colWidth = maxColWidth(numbers, j, cols);
Еще расскажи какой есть 3 способ объявления переменной и в чем они все различаются

2022-09-11 18:16 UTC, Shureks-den requested changes

2022-09-11 18:16 UTC, Shureks-den commented on source/format.js
> +function format(numbers, cols) {
Еще нужно добавить jsdoc

2022-09-11 18:23 UTC, Shureks-den commented on source/format.js
> +function maxColWidth(numbers, col, colsNumber) {
И еще кажется, что ее можно вызвать 1 раз только вначале, а не каждый раз пересчитывать, что усложняет алгоритмическую сложность

2022-09-11 19:57 UTC, Aralary commented on source/format.js
> +function maxColWidth(numbers, col, colsNumber) {
добавляем ее в начало файла чтобы работа была в современном режиме(например в современном режиме могли оптимизировать какие то функции или добавить новые)

2022-09-11 19:57 UTC, Aralary commented on source/format.js
> +            if (j < cols - 1 && numbers[i + j] !== numbers[numbers.length - 1]) {
добавил но выглядит если честно нечитабельно

2022-09-12 13:47 UTC, Aralary commented on source/format.js
> +            }
сделано

2022-09-12 13:52 UTC, Aralary commented on source/format.js
> +function format(numbers, cols) {
сделано. Используя синтаксис стрелочной функции, мы не создаем именованные функции а создаем функтор - переменную через которую сможем вызывать функцию которую написали. Также у стрелочных функций нет this

2022-09-12 20:26 UTC, Aralary commented on source/format.js
> +function maxColWidth(numbers, col, colsNumber) {
через  arr.map там трабл (элементы массива, длины которых надо форматировать, лежат не попрорядку и слайсами с мапом не отделаться там и просто мапом не отделаться тк надо не весь массив редактировать )

2022-09-12 20:27 UTC, Aralary commented on source/format.js
> +function maxColWidth(numbers, col, colsNumber) {
сделал лучше чем было

2022-09-12 20:30 UTC, Aralary commented on source/format.js
> +            let colWidth = maxColWidth(numbers, j, cols);
переписал эту часть и добавил конст к массиву длин столбиков. есть еще var но он гейский какой-то: област его видимости либо вся функция в которой объявления переменная таким образом или весь скрипт(ему все равно на '{}' ) и инициализация переменной происходит в начале ее области видимости даже если в коде она объявлена гораздо ниже. это сильно ломает структуру кода

2022-09-12 20:31 UTC, Aralary commented on source/format.js
> +        for (let j = 0; (j < cols) && (i + j < numbers.length); ++j) {
попробовал упростить но методами массива тут не обойтись

2022-09-12 20:31 UTC, Aralary commented on source/format.js
> +
вроде добавил

2022-09-12 20:56 UTC, Aralary commented on source/format.js
> +function format(numbers, cols) {
добавил

2022-09-13 08:56 UTC, Shureks-den requested changes

2022-09-13 08:56 UTC, Shureks-den commented on source/format.js
> +let format = (numbers, cols) => {
Сделай константой, ты же меняешь ее

2022-09-13 08:56 UTC, Shureks-den commented on source/format.js
> +        throw e;
Давай сделаем проверку в этой функции через array.every

2022-09-13 08:56 UTC, Shureks-den commented on source/format.js
> +        for (let j = i; j < numbers.length; j += colsCount) {
Можешь вынести из цикла инициализации и сделать типо такого `  const cols = new Array(colN);
  for (let i = 0; i < colN; ++i) {
    cols[i] = [];
  }
  nums.foreach(elem) {
    cols[i % colN].push(elem);
  }
  `

2022-09-13 08:56 UTC, Shureks-den commented on source/format.js
> +        for (let j = i; j < numbers.length; j += colsCount) {
И потом уже через map и math.max собрать это в массив длин

2022-09-13 08:56 UTC, Shureks-den commented on source/format.js
> +                    (j === cols - 1 && i + j !== numbers.length - 1) ? res += '\n' : false;
Это можно заменить на padstart и сделать только if проверку на \n

2022-09-13 14:54 UTC, Shureks-den requested changes

2022-09-13 14:54 UTC, Shureks-den commented on source/format.js
> +        if (!isFinite(numbers[i])) {
Все еще предлагаю вынести эту проверку на уровень другой функции через every

2022-09-13 14:54 UTC, Shureks-den commented on source/format.js
> +    for(let i = 0; i < numbers.length; ++i) {
Давай заменим на numbers.forEach((num, idx) =>

2022-09-13 14:54 UTC, Shureks-den commented on source/format.js
> +    return colsWidths;
Давай этот кусок заменим на return colsWidths.map => Math.max...

2022-09-13 16:07 UTC, Shureks-den requested changes

2022-09-13 16:07 UTC, Shureks-den commented on source/format.js
> +    try {
Можно убрать теперь отсюда trycatch

2022-09-13 17:30 UTC, Shureks-den requested changes

2022-09-13 17:30 UTC, Shureks-den commented on source/format.js
> +        let temp = Number(el);
const + назови num/number

2022-09-13 17:30 UTC, Shureks-den commented on source/format.js
> +            index < numbersChecked.length - 1 && index % cols === cols - 1 ? res += '\n' : false;
Можно заменить все на ` res += String(nums[i]).padStart(maxColLens[index % cols]) + ' ';` + 
`    if (index % cols=== cols - 1) {
      res += '\n';
    }`

2022-09-13 17:30 UTC, Shureks-den commented on source/format.js
> +            index < numbersChecked.length - 1 && index % cols === cols - 1 ? res += '\n' : false;
И вынеси index % cols в отдельную переменную

2022-09-13 17:30 UTC, Shureks-den commented on source/format.js
> +
Добавь тест, чтобы не было вроде :)

2022-09-13 17:35 UTC, Shureks-den requested changes

2022-09-13 17:35 UTC, Shureks-den commented on source/format.js
> +}
Добавь пустую строку

2022-09-13 19:22 UTC, Shureks-den requested changes

2022-09-13 19:22 UTC, Shureks-den commented on source/format.js
> +        let i = index % cols;
const

2022-09-13 19:22 UTC, Shureks-den commented on source/format.js
> +        !endFlag && !rowEnd ? res += ' ' : false;
Может тогда` if (endFlag) return; res += rowEnd ? '\n' : ' '`

2022-09-13 19:42 UTC, Shureks-den requested changes

2022-09-13 19:42 UTC, Shureks-den commented on source/format.js
> +        let rowEnd = (i === cols - 1);
Тут тоже const :)

2022-09-13 19:42 UTC, Shureks-den commented on source/format.js
> +        if (index === numbersChecked.length - 1) { return; }
тут можно убрать скобки { }

2022-09-13 19:42 UTC, Shureks-den commented on tests/format.js
> +    QUnit.test('format работает правильно c одной колонкой и числами разного знака', function (assert) {
Тест повторяет прошлые, он не нужен

2022-09-13 19:51 UTC, Shureks-den requested changes

2022-09-13 19:51 UTC, Shureks-den commented on source/format.js
> +    if(cols > numbers.length || cols < 1){throw Error("incorrect number of cols");}
Форматирование поехало

2022-09-13 20:00 UTC, Shureks-den approved these changes

2022-09-13 23:16 UTC, Shureks-den requested changes

2022-09-13 23:16 UTC, Shureks-den commented on source/format.js
> +        res += String(el).padStart(widths[i]);
В остальных местах забыл название на новое поменять

2022-09-13 23:19 UTC, Aralary commented on source/format.js
> +        res += String(el).padStart(widths[i]);
Поправил)

2022-09-14 15:25 UTC, Shureks-den approved these changes

2022-09-14 15:30 UTC, Betchika99 commented
ДЗ принято. На будущее - используй пожалуйста отступы между смысловыми блоками кода. так читаться будет проще :)

2022-09-14 15:30 UTC, closed without merging