Урванцев Захар вариант 5
frontend-park-mail-ru/homework_2022_2 pull request #4
Opened 2022-09-04 20:39 UTC by Zuhropenchik

2022-09-04 22:04 UTC, DPeshkoff requested changes
Привет!
Поздравляю с переходом на второй семестр и добро пожаловать на курс фронтенд-разработки)
Решение неплохое, но нужно кое-что исправить - оставил несколько комментариев. Если возникнут какие-то вопросы, можешь писать здесь или в [Телеграм](https://t.me/DmPesh))

2022-09-04 22:04 UTC, DPeshkoff commented on source/chess.js
> +}
Давай добавим перенос строки в конце файла ([почему это важно](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline/729795#729795))

2022-09-04 22:04 UTC, DPeshkoff commented on tests/chess.js
> +		assert.strictEqual(chess(-5), null);
"Аргумент должен быть положительным числом", а ты передаешь -5

Ловушка!

2022-09-04 22:04 UTC, DPeshkoff commented on tests/chess.js
> +	});
А что будет, если мы передадим, например, NaN, +Infinity, -Infinity, null, undefined?

2022-09-04 22:04 UTC, DPeshkoff commented on source/chess.js
> +    return null;
А почему ты выбрал возврат null, а не выбрасывание ошибки?

2022-09-05 11:32 UTC, Zuhropenchik commented on source/chess.js
> +const chess = (n) => {
У стрелочных функций нет this, в данном случае он не нужен.

2022-09-05 17:59 UTC, Zuhropenchik commented on source/chess.js
> +
Включается строгий режим, во время которого программировать безопаснее, так как выбрасываются некоторые ошибки, которые не выбрасывались бы в "старом" режиме

2022-09-06 17:43 UTC, DPeshkoff requested changes
Уже лучше, но нужно кое-что еще поправить

2022-09-06 17:43 UTC, DPeshkoff commented on source/chess.js
> + * бесконечного
Давай добавим описание и примеры использования

2022-09-06 17:43 UTC, DPeshkoff commented on source/chess.js
> +  if(n === null) {
Можно не проверять только на [null](https://developer.mozilla.org/en-US/docs/Glossary/Falsy))

2022-09-06 17:43 UTC, DPeshkoff commented on source/chess.js
> +    throw new Error("Пустое значение аргумента функции chess");
Можно лучше - можно выбрасывать не просто [Error](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error#error_types)

Кстати, обычно в JS используют ' '
Но это так, не критично)

2022-09-06 17:43 UTC, DPeshkoff commented on source/chess.js
> +  if(!Number.isInteger(Number(n))){
Не обязательно приводить к Number внутри isInteger - она вернет false, если это не число)

И по важности это более приоритетная проверка, чем `n<1 || n>100`

2022-09-06 17:43 UTC, DPeshkoff commented on source/chess.js
> + * @returns {string}
У тебя остался один кейс, где возвращается null
А тут не отразил

2022-09-06 17:43 UTC, DPeshkoff commented on source/chess.js
> +  firstStr = firstStr.repeat(Math.ceil(n/2) - 1).padEnd(n-1, "*");
А давай и это под цикл на 32 строке занесем? Тогда нам не нужна будет переменная, а код будет понятнее

2022-09-06 17:43 UTC, DPeshkoff commented on source/max.js
> +const max = numbers => Math.max(...numbers);
А почему тут diff?(

2022-09-06 17:58 UTC, DPeshkoff commented on source/chess.js
> +
Мысль верная, но кажется, что выбрасывание ошибок - это следствие)

Бонусный интересный вопрос - а в консоли браузера строгий режим?)

2022-09-06 17:59 UTC, Zuhropenchik commented on source/chess.js
> +  if(!Number.isInteger(Number(n))){
isInteger не сможет обработать аргументы типа "23", '5', он их не воспринимает как число

2022-09-06 18:42 UTC, Zuhropenchik commented on source/chess.js
> +
По умолчанию нет. Вообще когда работаешь с множеством модулей, иногда его нет смысла включать, так как внутри модулей он может работать и так

2022-09-07 08:38 UTC, DPeshkoff requested changes
Осталось совсем чуть-чуть)

2022-09-07 08:38 UTC, DPeshkoff commented on source/chess.js
> + * @returns {null}
string он тоже возвращает)
напиши оба через |

2022-09-07 08:38 UTC, DPeshkoff commented on source/chess.js
> +  if(!Number.isInteger(Number(n))){
Тогда, если очень хочешь преобразовывать строки - то лучше оптимизировать. Сейчас у тебя два раза происходит Number(n)

Ты можешь вынести его повыше и проверять на NaN

2022-09-07 08:38 UTC, DPeshkoff commented on source/chess.js
> +  if(n==1){
Давай немного поправим кодстайл в файле, а то везде как-то немного по-разному получилось

[Ссылка на стайлгайд по плюсам от Гугла](https://google.github.io/styleguide/jsguide.html) (ну почти по плюсам)

2022-09-07 20:41 UTC, DPeshkoff requested changes

2022-09-07 20:41 UTC, DPeshkoff commented on source/chess.js
> +  if(!Number.isInteger(Number(n))) {
тут случайно Number(n) остался

2022-09-07 20:41 UTC, DPeshkoff commented on source/chess.js
> +  if(n == 1) {
Лучше [===](https://developer.mozilla.org/ru/docs/Web/JavaScript/Equality_comparisons_and_sameness)

2022-09-07 21:09 UTC, DPeshkoff approved these changes

2022-09-10 22:05 UTC, DPeshkoff requested changes
Проглядел еще чуть-чуть)

2022-09-10 22:05 UTC, DPeshkoff commented on source/chess.js
> +  if(n === 1) {
Давай поправим пробелы в if)

2022-09-10 22:05 UTC, DPeshkoff commented on source/chess.js
> +  n = Number(n);
Давай сделаем функцию чистой)

2022-09-11 12:35 UTC, DPeshkoff requested changes

2022-09-11 12:35 UTC, DPeshkoff commented on source/chess.js
> +  let nNum = Number(n);
Кажется, эта переменная изменяться не будет

2022-09-11 12:35 UTC, DPeshkoff commented on source/chess.js
> +  for (let i=0; i<nNum; i++) {
Давай тут еще пробелов добавим)

2022-09-11 21:25 UTC, DPeshkoff approved these changes

2022-09-11 21:53 UTC, Betchika99 commented
ДЗ принято

2022-09-11 21:53 UTC, closed without merging