Александр Анофриков: 1
frontend-park-mail-ru/homework_2022_2 pull request #5
Opened 2022-09-05 12:32 UTC by Andeo1812

2022-09-05 14:42 UTC, Sarafa2n requested changes
Привет!
Поздравляю с переходом на второй семестр и добро пожаловать на курс фронтенд-разработки)
Решение неплохое, но нужно кое-что исправить - оставил несколько комментариев. Если возникнут какие-то вопросы, можешь писать здесь или в телеграм (sarafa2n)

2022-09-05 14:42 UTC, Sarafa2n commented on source/zip.js
> +    let result = {};
const

2022-09-05 14:42 UTC, Sarafa2n commented on source/zip.js
> +const zip = (...objects) => {
Респект за стрелочные функции, а какие еже есть ?

2022-09-05 14:42 UTC, Sarafa2n commented on source/zip.js
> +        if (typeof (objects[i]) != "object") {
не корректная проверка, посмотри что будет если сделать он new Array() или от new String

2022-09-05 14:42 UTC, Sarafa2n commented on source/zip.js
> +            throw new SyntaxError("Arguments must be objects");
не совсем правильный тип ошибки

2022-09-05 14:42 UTC, Sarafa2n commented on source/zip.js
> +    }
Разве мы не можем объединить объекты по-другому?

2022-09-05 14:42 UTC, Sarafa2n commented on source/zip.js
> +    for (let i = 0, length = objects.length; i < length; ++i) {
А давай здесь попробуем вместо for использовать один из мотодов массива

2022-09-05 15:51 UTC, Sarafa2n requested changes

2022-09-05 15:51 UTC, Sarafa2n commented on source/zip.js
> +const zip = (...objects) => {
а в чем отличие ?

2022-09-05 15:51 UTC, Sarafa2n commented on source/zip.js
> +    return objects.reduce(getUniqFields);
1. А мы можем сразу написать return reduce ? 
2. Давай вместо цикла перегона использовать spread оператор
3. А где дефолтное значение у reduce?

2022-09-05 15:51 UTC, Sarafa2n commented on source/zip.js
> +    let getUniqFields = function (res, cur) {
ну тут тоже const
и почему не стрелочная функция?

2022-09-05 15:51 UTC, Sarafa2n commented on source/zip.js
> +        if (!(cur instanceof Object)) {
ну это то же не оч
![image](https://user-images.githubusercontent.com/32399246/188484503-d6e86604-c51a-4d44-905b-b19065b60d91.png)

2022-09-05 17:19 UTC, Sarafa2n requested changes
нет тестов

2022-09-05 17:19 UTC, Sarafa2n commented on source/zip.js
> + * @throws исключения невалидных аргументов: Неправильные типы
нет типа исключения посмотри в доке

2022-09-05 17:19 UTC, Sarafa2n commented on source/zip.js
> +        }
смотри коммент выше

2022-09-06 09:03 UTC, Sarafa2n requested changes

2022-09-06 09:03 UTC, Sarafa2n commented on source/zip.js
> + *
нет входных переменных в jsdoc

2022-09-06 09:10 UTC, Sarafa2n requested changes

2022-09-06 09:10 UTC, Sarafa2n commented on source/zip.js
> +    if (objects.length === 0) {
можно просто !objects.length

2022-09-06 20:11 UTC, Betchika99 commented
ДЗ принято

2022-09-06 20:11 UTC, closed without merging