Кирпичов Владислав Variant 10
frontend-park-mail-ru/homework_2022_2 pull request #6
Opened 2022-09-05 16:29 UTC by VladislavKirpichov

2022-09-05 18:46 UTC, Shureks-den commented
Привет, я Саша. Я буду проверять твое дз, по всем вопросам или если поправил и не хочешь ждать, пока я чекну почту можешь писать в телегу https://t.me/alexklonov

2022-09-05 19:10 UTC, Shureks-den requested changes

2022-09-05 19:10 UTC, Shureks-den commented on source/letters.js
> +    if (typeof str !== "string") throw new Error("Некорректный тип данных")
Используешь разные типы скобок " ' лучше использовать всегда одиночные

2022-09-05 19:10 UTC, Shureks-den commented on source/letters.js
> +const deleteAllRepeatedSymbols = (str) => {
Аналогично saveFirstLetters

2022-09-05 19:10 UTC, Shureks-den commented on source/letters.js
> +    if (flag) {
Давай заюзаем тернарный оператор типо return flag ? ... : ...

2022-09-05 19:10 UTC, Shureks-den commented on source/letters.js
> +    if (flag === undefined) {
Можно !flag

2022-09-05 19:10 UTC, Shureks-den commented on source/letters.js
> +}
Добавь пустую строку в конце :)

2022-09-05 19:10 UTC, Shureks-den commented on source/letters.js
> +    for (let i in str) {
Аналогично saveFirstLetters

2022-09-05 19:10 UTC, Shureks-den commented on source/letters.js
> +}
Вообще субъективно, но все вспомогательные функции ты вызываешь в одной основной, поэтому давай их перенесем в тело этой функции, обычно в одном файле больше одной функции и много "публичных"(с натяжкой, это конечно не публичные методы) иногда сбивает с толку

2022-09-05 19:10 UTC, Shureks-den commented on source/letters.js
> +}
Ну и парочка вопросов на js:
1) Расскажи про строгий режим, для чего он нужен и нужен ли вообще
2) Уже задал вопрос про сложные объекты, дополни его - чем еще поведение таких объектов отличается от примитивов
3) Почему используешь именно такой синтаксис функции, есть ли еще способ задать функцию?
4) Изменяешь ли исходную строку(тут вопрос скорее на логику .split)

--------
upd: подумал, что для проверок вхождения можно завести set или мапу, если заюзаешь их вообще огонь будет

2022-09-05 19:48 UTC, VladislavKirpichov commented on source/letters.js
> +            res.push(str[i])
const задает константную ссылку на массив. const не позволяет присвоить данному объекту(массиву) другое значение, однако операции над элементами массива и его изменение можно делать.

2022-09-05 19:49 UTC, VladislavKirpichov commented on source/letters.js
> +    if (flag === undefined) {
Просто по условию задачи ,если флаг не передали, то нужно удалить все повторяющиеся символы

2022-09-05 20:00 UTC, VladislavKirpichov commented on source/letters.js
> +}
1. "use strict" - добавляет совместимость со старыми версиями js + не дает js игнорировать ошибки и выдает исключения. Нужен для совместимости со старыми версиями js и для "отлова" ошибок
2. Сложный объект может хранить в себе примитвы и ссылки на другие сложные объекты(свойства). К ним можно обращаться через . или через вычисляемые свойства. Примитивы это по сути просто данные (как int или char* в си), они не имеют методов работы с ними(но при обращении к ним через . создаются временные объекты String например, которые как раз имеют методы для работы с примитивами).
3. Есть function declaration - такие функции создаются в начале программы еще до выполнения кода (как var)
4. Нет, в js строки иммутабельны

2022-09-05 20:14 UTC, Shureks-den requested changes

2022-09-05 20:14 UTC, Shureks-den commented on source/letters.js
> +    return res;
Можно заменить последние 3 строчки - убери res и сделай тернарный оператор прямо в return

2022-09-05 20:14 UTC, Shureks-den commented on source/letters.js
> +        if (str.some((elem) => elem !== temp)) return false;
Можно убрать return false, а возвращать сразу результат функции str.some или !str.some

2022-09-05 20:14 UTC, Shureks-den commented on source/letters.js
> +        const res = str.split('').filter((value, index, self) => {
Необязательно заводить переменную, зачейни методы

2022-09-05 20:26 UTC, Shureks-den approved these changes

2022-09-06 08:40 UTC, Shureks-den requested changes

2022-09-06 08:40 UTC, Shureks-den commented on source/letters.js
> +    const isStrConsistsOfOneChar = (str) => {
Привет, это снова я, нашел еще пару моментов которые можно поправить. Это функция точно нужна? А то выглядит как костыль, потому что алгоритм должен работать и без нее

2022-09-06 08:40 UTC, Shureks-den commented on source/letters.js
> +            return self.lastIndexOf(value) === self.indexOf(value);
Эти три функции выглядят практически одинаково, а их вызов зависит от флага, давай добавим параметр flag, будет передавать в одну общую функцию и внутри нее выбирать логику работу. Думаю для такого может помочь, что методы объектов можно вызывать иначе, твоя задача узнать как :)

2022-09-06 08:40 UTC, Shureks-den commented on source/letters.js
> +    if (typeof str !== 'string') throw new TypeError('Некорректный тип str');
Этот блок проверок перенеси до инициализации всех функций - если проверка не пройдет, функции не будут созданы === не выделится лишняя память

2022-09-06 08:40 UTC, Shureks-den commented on source/letters.js
> +    if (flag === undefined) return saveOnlyUniqueLetters(str);
Не хватает проверок, что это действительно boolean, можно например по ошибке передать строку, и она сработает как true из за тайпкастов

2022-09-06 08:40 UTC, Shureks-den commented on tests/letters.js
> +	QUnit.test('Проверка на некорректные данные', function (assert) {
И давай добавим еще тестов, например новые тесты на флаг + на строку состоящею из 1 символа

2022-09-06 17:20 UTC, Shureks-den requested changes

2022-09-06 17:20 UTC, Shureks-den commented on source/letters.js
> +    const saveOnlyUniqueLetters = (str) => {
Эти две функции тоже можно в одну объединить, сохранить правую часть сравнения === в переменную, в зависимости от флага типо const compare(или как лучше в твоем случае назвать переменную) = flag === undefined ? index : self...

2022-09-06 17:20 UTC, Shureks-den commented on source/letters.js
> +    if (str === '') return '';
Ты точно уверен, что это проверка нужна, кажется и без нее можно

2022-09-06 17:20 UTC, Shureks-den commented on tests/letters.js
> +	QUnit.test('Проверка на строку состояющую из одного символа', function (assert) {
Я скорее имел в виду много повторений одного символа, но эти тесты тоже можно оставить

2022-09-06 17:47 UTC, Shureks-den commented on source/letters.js
> +    const saveOnlyUniqueLetters = (str) => {
Или вызывать сразу тернарный оператор в правой части

2022-09-06 18:11 UTC, VladislavKirpichov commented on source/letters.js
> +    const saveOnlyUniqueLetters = (str) => {
Я в итоге убрал дополнительные функции и добавил проверку флага в filter

2022-09-06 18:11 UTC, VladislavKirpichov commented on tests/letters.js
> +	QUnit.test('Проверка на строку состояющую из одного символа', function (assert) {
Добавил тесты в которых много раз повторяется символ

2022-09-06 18:24 UTC, Shureks-den commented on source/letters.js
> +    const saveOnlyUniqueLetters = (str) => {
Да, вижу, как по мне теперь немного перемудрили, давай для лучшей читаемости все таки прямо в filter'е заведем переменную для правой части и с ней будем сравнивать 
![image](https://user-images.githubusercontent.com/65308659/188710407-fb36ce79-c181-4c43-a95d-98d86449da56.png)
Сохранив примерно прошлую структуру

2022-09-06 18:24 UTC, Shureks-den commented on source/letters.js
> +    const saveOnlyUniqueLetters = (str) => {
const comparisonValue = flag ? index : ...

2022-09-06 19:14 UTC, Shureks-den approved these changes

2022-09-06 19:57 UTC, Betchika99 commented
ДЗ принято

2022-09-06 19:57 UTC, closed without merging