Пак Леонард Вариант 2
frontend-park-mail-ru/homework_2022_2 pull request #8
Opened 2022-09-05 18:43 UTC by MrLeonardPak

2022-09-05 19:14 UTC, Shureks-den commented
Привет, я Саша. Буду проверять твое дз, в случае если буду замечания по реквесту и ты их поправишь и не захочешь ждать, пока я чекну почту или гитхаб, можешь написать мне в тг https://t.me/alexklonov

2022-09-05 19:42 UTC, Shureks-den requested changes

2022-09-05 19:42 UTC, Shureks-den commented on index.html
> +	<script src="source/max.js"></script>
Раз ты поменял html файлик, то убери max.js, это лишь для примера служило 👍

2022-09-05 19:42 UTC, Shureks-den commented on source/euclid.js
> +  let local_num_1 = +num_1;
Не понял, зачем после = стоит +, похоже на typo

2022-09-05 19:42 UTC, Shureks-den commented on source/euclid.js
> +  let local_num_2_ = +num_2;
На js никто не использует snake_case, а стандартом признан camelCase. Тем более, у тебя оба этих стиля используются, не надо так :(

2022-09-05 19:42 UTC, Shureks-den commented on source/euclid.js
> + * @param  {...any} num_arr - array of natural number
Наверно тут тип number должен быть

2022-09-05 19:42 UTC, Shureks-den commented on source/euclid.js
> +  }
Как мне кажется тут дублирование кода на ровном месте, а такое никто не любит. Давай используем продвинутый js и сделаем функцию с замыканием, которая будет принимать два параметра - функцию, которая возвращает boolean и название переменной строкой. Сама функция, должна возвращать тоже функцию, которая принимает number и вызывает твои проверки из замыкания. Концепция достаточно сложная, но очень полезная

2022-09-05 19:42 UTC, Shureks-den commented on source/euclid.js
> +    } else {
Тут тоже можно заменить на тернарный оператор

2022-09-05 19:42 UTC, Shureks-den commented on source/euclid.js
> +
Дал сложное задание, жду что ты его поймешь и осознаешь или спросишь, если совсем забуксуешь. Но пару простых вопросиков на теорию все же задам :) 
1) Расскажи, что делает первая строка :)
2) Объясни (а может и поправь) в чем отличия в способе создания функций euclid и euclidRaw;
3) Какие есть ключевые слова для объявления переменных и что каждое из них делает

2022-09-06 08:58 UTC, MrLeonardPak commented on source/euclid.js
> +  let local_num_1 = +num_1;
Для преобразования к числу, если это возможно. Брал отсюда [Приведение к числу, унарный +](https://learn.javascript.ru/operators#privedenie-k-chislu-unarnyy)

2022-09-06 08:59 UTC, MrLeonardPak commented on source/euclid.js
> +  let local_num_2_ = +num_2;
Привычка с хромиум стайла по плюсам, поправил

2022-09-06 09:01 UTC, MrLeonardPak commented on source/euclid.js
> +  }
Понял про замыкания, но сделал чуть по другому. Не вижу смысла передавать в функцию имя переменной, так как  это привязывает замыкание к самой переменной

2022-09-06 09:02 UTC, MrLeonardPak commented on source/euclid.js
> +    } else {
Не уверен. Присваивание в зависимости от условия происходит к разным переменным. В итоге с тернарным оператором получится их два и то обрезанных

2022-09-06 09:28 UTC, MrLeonardPak commented on source/euclid.js
> +
1) Директива 'use strict' используется для перехода в строгий режим, где проверка кода проходит "пристальнее" ,а также подключается современные возможности js.
2) euclidRaw создана как function declaration. Такие функции создаются до старта всего скрипта и могут быть вызваны из любой строчки в области видимости
    euclid создана как arrow function. Такие функции чаще используются для однострочных задач, они не имеют своего контекста (this, arguments)
3) let - создает переменную, которую можно изменять в процессе всей программы. По умолчанию undefined
    const -  создает переменную, которую нельзя изменять в процессе программы. Требует определения при объявлении
    var - устаревшая нотация. Похожа на let, но имеет отличия: 
    - объявление переменной перед стартом скрипта/функции (можно использовать переменную, а объявить её в самом конце)
    - максимальное ограничение видимости - тело функции, при создании в цикле или условии, переменная будет видна вне блока кода

2022-09-06 17:38 UTC, Shureks-den requested changes

2022-09-06 17:38 UTC, Shureks-den commented on source/euclid.js
> +  let errStrNum = ' is not a number';
Много где используешь let вместо const,

2022-09-06 17:38 UTC, Shureks-den commented on source/euclid.js
> +    } else {
![image](https://user-images.githubusercontent.com/65308659/188701462-2c856831-4053-4ad7-8824-1d85bcc3bde0.png)
Почему? Вот

2022-09-06 17:38 UTC, Shureks-den commented on source/euclid.js
> +  return (num1 == 0) ? num2 : num1;
Лучше использовать === и !== для сравнения, а в твоем случае можно обойтись без знаков сравнения num1? ... (логика оператора)

2022-09-06 17:38 UTC, Shureks-den commented on source/euclid.js
> +    let numLocal = +num;
Еще мне не очень нравятся названия переменных, нужно смотреть код сначала, чтобы понять для чего они. Тут например можно назвать numConverted, numCasted или как то еще, чтобы понять для чего эта переменная. Тоже с текстом ошибки, лучше сначала показать что это за ошибка, а потом уже пояснение notNaturalErrText к примеру

2022-09-06 17:38 UTC, Shureks-den commented on source/euclid.js
> +    let numLocal = +num;
И вот тут немного javascript ninja пошло, для большей читаемости лучше приводит строку к числу не через унарный плюс, а через конструктор Number. Поведение аналогичное, а читаемость выше будет

2022-09-07 07:28 UTC, Shureks-den requested changes

2022-09-07 07:28 UTC, Shureks-den commented on source/euclid.js
> +  num1 = checkerNatNum(num1);
Давай для этих чисел заведем новые переменные, и название подчеркнет, что это точно тип number

2022-09-07 07:32 UTC, Shureks-den commented on source/euclid.js
> +  num1 = checkerNatNum(num1);
И еще давай уберем числа из названий, пусть это будет firstValue, secondValue

2022-09-07 07:54 UTC, Shureks-den requested changes

2022-09-07 07:54 UTC, Shureks-den commented on source/euclid.js
> +function makeIsNatureNumber(checkNatNum) {
Давай последний рывок с неймнигами, назовем эту функцию validate

2022-09-07 07:54 UTC, Shureks-den commented on source/euclid.js
> +function makeIsNatureNumber(checkNatNum) {
Давай последний рывок с неймингами, назовем функцию validateNumber

2022-09-07 07:54 UTC, Shureks-den commented on source/euclid.js
> +  let firstValidNum = checkerNatNum(firstValue);
И тут тогда без valid, потому что из названия функции будет ясно

2022-09-07 07:54 UTC, Shureks-den commented on source/euclid.js
> +  const checkerNatNum = makeIsNatureNumber(isNaturalNumber);
А эту назовем numberValidator или как нибудь похоже

2022-09-07 08:10 UTC, Shureks-den approved these changes

2022-09-07 20:23 UTC, Shureks-den requested changes

2022-09-07 20:23 UTC, Shureks-den commented on source/euclid.js
> +function makeValidatorNatureNumber(checkNaturalFunc) {
Привет, это снова я) Есть два еще небольших замечания - так как нам не важны в данных функциях this и arguments, то давай их в стрелочном типе перепишем

2022-09-07 20:23 UTC, Shureks-den commented on source/euclid.js
> +  while ((firstNum > secondNum) ?
Хорошое решение с точки зрения лакончиности, но не очень с точки зрения код стайла, оставлять пустой блок {}. Давай как нибудь изменим этот цикл, чтобы не было такого как вариант вернуться к прошлому варианту, оставив тернарный оператор. Если у тебя будет такое же лаконичное решение, при этом не ломаю логику условных операторов, то я только за

2022-09-08 12:13 UTC, Shureks-den approved these changes

2022-09-10 22:03 UTC, Betchika99 commented
ДЗ принято, но в будущем чаще используй стрелочные функции :)

2022-09-10 22:03 UTC, closed without merging