Михаил Ходосов: вариант 7
frontend-park-mail-ru/homework_2022_2 pull request #9
Opened 2022-09-05 19:33 UTC by lonkidely

2022-09-05 19:46 UTC, Shureks-den commented
Привет, меня зовут Саша, я буду проверять твое дз. По всем вопросам можешь стучать в https://t.me/alexklonov

2022-09-05 19:47 UTC, Shureks-den requested changes

2022-09-05 19:47 UTC, Shureks-den commented on source/plain.js
> +const plain = (array) => array.flat(Infinity);
Круто, что знаешь методы прототипов, но само задание состоит в реализации похожего функционала, поэтому я попрошу тебя реализовать эту функцию без использования plain

2022-09-06 09:56 UTC, Sarafa2n requested changes

2022-09-06 09:56 UTC, Sarafa2n commented on tests/plain.js
> +		);
давай напишем больше тестов

2022-09-06 09:56 UTC, Sarafa2n commented on source/plain.js
> +    const stack = [...array];
а что будет если придут не валидные данные ?

2022-09-06 10:49 UTC, lonkidely commented on source/plain.js
> +    return result_array.reverse();
сделано

2022-09-06 10:50 UTC, lonkidely commented on tests/plain.js
> +		);
дописал, в т.ч. покрыл тестами проверку входных данных

2022-09-06 10:51 UTC, lonkidely commented on source/plain.js
> +    const stack = [...array];
учтено, добавлены проверки

2022-09-06 13:43 UTC, Sarafa2n requested changes

2022-09-06 13:43 UTC, Sarafa2n commented on source/plain.js
> +    if (args.length > 0) {
а если !args.length ?

2022-09-06 13:43 UTC, Sarafa2n commented on source/plain.js
> +    return depth > 0 ? array.reduce((acc, val) => acc.concat(Array.isArray(val) ? flatArray(val, depth - 1) : val), []) : array.slice();
а давай разобьем на несколько строк

2022-09-06 13:43 UTC, Sarafa2n commented on source/plain.js
> +const flatArray = (array, depth) => {
кажется лишняя функция можно в основной так сделать

2022-09-06 16:21 UTC, lonkidely commented on source/plain.js
> +    if (args.length > 0) {
Поправил, по логике их в принципе быть не должно, поэтому без отрицания сойдет

2022-09-06 16:21 UTC, lonkidely commented on source/plain.js
> +    return depth > 0 ? array.reduce((acc, val) => acc.concat(Array.isArray(val) ? flatArray(val, depth - 1) : val), []) : array.slice();
Вроде читабельнее стало, поправил)

2022-09-06 16:23 UTC, lonkidely commented on source/plain.js
> +const flatArray = (array, depth) => {
Основную функцию вызывают без указания глубины, ну и всё-таки flatArray решает конкретную задачу, в то время как plain ещё и проверяет валидность данных. Стоит ли заносить внутрь?

2022-09-06 18:55 UTC, Sarafa2n commented on source/plain.js
> +const flatArray = (array, depth) => {
ну тогда можно написать по-другому немного, стрелочная функция может сразу вернуть значение

2022-09-06 21:45 UTC, Betchika99 commented
ДЗ принято

2022-09-06 21:45 UTC, closed without merging